example/android/app/src/main/java/com/example/MainActivity.java, example/ios/Podfile.lock, example/package.json, example/storybook/stories/Navigation.stories.tsx, example/storybook/stories/OAuth.stories.tsx, example/storybook/stories/index.ts, example/yarn.lock, package.json, src/hooks/useAuth.test.tsx, src/hooks/useAuth.tsx, yarn.lock
https://user-images.githubusercontent.com/1445395/217888443-08a5091f-cbc5-40a0-b4e6-2e24ba2ba2ca.mp4
=> Add @react-navigation/native and demo story

.github/workflows/pull-request.yml, example/storybook/stories/AppDemo.stories.tsx, index.ts, src/index.ts, tsconfig.build.json, tsconfig.json
Resolves [this build failure](https://github.com/lifeomic/react-native-components/actions/runs/4147208110/jobs/7173808179).
=> fix: Resolve tsconfig issue with lib folder

example/babel.config.js, example/package.json, example/storybook/stories/AppDemo.stories.tsx, example/yarn.lock, index.ts, package.json, src/hooks/useAPIClients.test.tsx, src/hooks/useAPIClients.tsx, src/hooks/useAccounts.test.tsx, src/hooks/useAccounts.tsx, src/hooks/useActiveAccount.test.tsx, src/hooks/useActiveAccount.tsx, src/index.ts, src/screens/SettingsScreen.test.tsx, src/screens/SettingsScreen.tsx, yarn.lock
- Add react-query
- useAccounts, useActiveAccount
- Settings screen shows account name
=> Two hooks for accounts, and show account name on Settings screen

example/storybook/stories/AppDemo.stories.tsx, src/hooks/useAccounts.tsx, src/hooks/useHttpClient.test.tsx, src/hooks/useHttpClient.tsx, src/hooks/useMe.test.tsx, src/hooks/useMe.tsx, src/hooks/useUser.test.tsx, src/hooks/useUser.tsx, src/hooks/useUserProfile.test.tsx, src/hooks/useUserProfile.tsx, src/index.ts, src/screens/SettingsScreen.test.tsx, src/screens/SettingsScreen.tsx
- useUser (pure API) hook
- useMe (pure API) hook
- useUserProfile (some logic) hook
- (temp) Settings screen updates to demonstrate userProfile usage
=> chore: hooks and screen updates to demonstrate user-profile functionality

__mocks__/@react-navigation/native.ts, example/AppDemo.tsx, example/babel.config.js, example/index.js, jest.config.js, jest.setup.ts, package.json, src/common/index.ts, src/components/ActivityIndicatorView.test.tsx, src/components/ActivityIndicatorView.tsx, src/components/index.ts, src/hooks/index.ts, src/hooks/useUserProfile.tsx, src/index.ts, src/navigators/SettingsStack.tsx, src/navigators/index.ts, src/screens/ProfileScreen.test.tsx, src/screens/ProfileScreen.tsx, src/screens/SettingsScreen.test.tsx, src/screens/SettingsScreen.tsx, src/screens/index.ts, yarn.lock
https://user-images.githubusercontent.com/1445395/219216450-8d1bef15-35cd-440a-8ed5-1587073ec1d1.mp4
=> chore: ProfileScreen, AcrivityIndicatorView, some nav work

example/AppDemo.tsx, jest.config.js, src/common/LoggedInProviders.tsx, src/common/RootProviders.tsx, src/common/index.ts, src/navigators/RootStack.tsx, src/navigators/index.ts, src/screens/LoginScreen.tsx, src/screens/index.ts
- Define simple providers & stack helpers
- Reuse those so that AppDemo.tsx looks more like what we'll want in react-native-starter
=> chore: Providers, RootStack, dummy LoginScreen

__mocks__/@react-navigation/native.ts, src/hooks/useActiveAccount.tsx, src/hooks/useUserProfile.test.tsx, src/navigators/SettingsStack.tsx, src/screens/AccountSelectionScreen.test.tsx, src/screens/AccountSelectionScreen.tsx, src/screens/SettingsScreen.test.tsx, src/screens/SettingsScreen.tsx, src/screens/index.ts
- Add AccountSelectionScreen
- Integrate account selection into SettingsScreen
https://user-images.githubusercontent.com/1445395/219350196-83c09e5f-0854-4efe-a055-aa079e99fa69.mp4
=> chore: Support for account selection

README.md, example/babel.config.js, example/package.json, example/yarn.lock, package.json, src/navigators/HomeStack.tsx, src/navigators/RootStack.tsx, src/navigators/SettingsStack.tsx, src/navigators/TabNavigator.tsx, src/navigators/index.ts, src/screens/HomeScreen.tsx, src/screens/ProfileScreen.test.tsx, src/screens/ProfileScreen.tsx, src/screens/index.ts, yarn.lock
- Skeleton of HomeScreen and HomeStack
- Skeleton of TabNavigator
I started with a TabNavigator that looked more like what we have currently, with `TabBar` and `TabBarButton` components etc.  I got a warning where react detected that we were creating components within a render.  I'm not sure/convinced that's actually true, but I went ahead and simplified to what I have in this PR.  Seeing it in its simplest form like this, I'm excited to see how far we can take it using the `bottom-tabs` lib and NOT write those `TabBar` & `TabBarButton` components - we'll see.
https://user-images.githubusercontent.com/1445395/219382293-d34a8d90-3a6c-4759-a05b-1544e36e4f53.mp4
https://user-images.githubusercontent.com/1445395/219382308-34da1978-3985-4db8-9558-bb80828a24d2.mov
=> chore: HomeStack skeleton, TabNavigator

README.md, src/components/tiles/Tile.tsx, src/hooks/useAppConfig.test.tsx, src/hooks/useMe.test.tsx, src/hooks/useSubjectProjects.test.tsx, src/hooks/useSubjectProjects.tsx, src/screens/HomeScreen.test.tsx, src/screens/HomeScreen.tsx
- README tweaks
- Refactor view-only render of `Tile`
- Be more defensive in useSubjectProjects enabled prop
- Provide different loading messages while loading in HomeScreen
=> Cleanup from recent PRs

example/storybook/stories/Tile.stories.tsx, example/storybook/stories/index.ts
Full disclosure: really I just need a new npm publish after the repo rename.  OTOH, this is a skeleton of a story for the `Tile` component which we can build on over time.
=> fix: Skeleton of Tile demo story

example/storybook/index.ts, package.json, src/common/init.ts, src/screens/HomeScreen.tsx, src/screens/SettingsScreen.test.tsx, src/screens/SettingsScreen.tsx
- Fix up some default exports
- Add script to quickly test in starter repo
=> fix: Fix up some default exports, and add script to test in starter repo

src/hooks/useAuth.test.tsx, src/hooks/useAuth.tsx, src/hooks/useOAuthFlow.test.tsx, src/hooks/useOAuthFlow.tsx
- Refresh auth token, if needed, on app initialization
=> Refresh auth token, if needed, on app initialization

src/hooks/useAuth.test.tsx, src/hooks/useAuth.tsx, src/hooks/useCurrentAppState.tsx
- Refresh token, if needed, on app state change
=> Refresh token, if needed, on app state change

example/storybook/stories/BrandConfigProvider/BrandConfigProvider.stories.tsx, example/storybook/stories/BrandConfigProvider/ExampleBox.tsx, package.json, src/components/BrandConfigProvider/BrandConfigProvider.tsx, src/components/BrandConfigProvider/styles/StylesProvider.tsx, src/components/BrandConfigProvider/styles/useStyles.test.tsx, src/components/BrandConfigProvider/types.ts, src/hooks/index.ts, src/hooks/useStyles.ts, yarn.lock
-  [x] Initial styling system with typing
-  [x] Add tests and stories
-  [x] Clean up
https://user-images.githubusercontent.com/220893/222241612-3a3a817b-1a6f-4b24-a223-eb38af620c10.mov
=> PHC-4075 - Add styles provider

example/storybook/stories/NoInternetToastProvider.stories.tsx, src/hooks/NoInternetToastProvider.tsx
Remove extra prop used for Storybook and instead provide instructions on how to use the component in storybook.
=> chore: Remove test prop and add explanation to story

example/storybook/stories/BrandConfigProvider/BrandConfigProvider.stories.tsx, example/storybook/stories/BrandConfigProvider/ExampleBox.tsx, src/components/BrandConfigProvider/BrandConfigProvider.tsx, src/components/BrandConfigProvider/index.ts, src/components/BrandConfigProvider/styles/StylesProvider.tsx, src/components/BrandConfigProvider/styles/types.d.ts, src/components/BrandConfigProvider/styles/useStyles.test.tsx, src/components/OAuthLoginButton.tsx, src/screens/LoginScreen.tsx, tsconfig.json
- Clean up style types
This addresses some feedback from last PR, and is the basis for [this next PR](https://github.com/lifeomic/react-native-sdk/pull/67)
=> chore: Clean up style types

src/hooks/useActiveAccount.test.tsx, src/hooks/useActiveAccount.tsx, src/hooks/useAsyncStorage.ts, src/hooks/useGetAsyncStorage.ts
Light refactor to include setItem within the useAsyncStorage hook
=> PHC-4151 Include setItem in async storage hook

README.md
- Update Readme with xcodebuild command to clean build folder
=> PHC-4075 - Add xcodebuild clean example to readme

src/navigators/TabNavigator.tsx, src/screens/SettingsScreen.tsx
- Add style to settings screen
=> PHC-4075 - Add style to settings screen

src/components/BrandConfigProvider/styles/StylesProvider.tsx, src/components/BrandConfigProvider/styles/createStyles.ts, src/components/BrandConfigProvider/theme/ThemeProvider.tsx
Tweaks the types of the createStyles and useStyles functions to make them slightly more powerful and avoid some `any`s.
=> fix: PHC-4075 Minor Typing Tweaks

src/components/AppNavHeader.tsx, src/navigators/HomeStack.tsx, src/navigators/SettingsStack.tsx, src/navigators/TabNavigator.tsx
- Update navigation header
https://user-images.githubusercontent.com/220893/225091538-513b22cf-fdbe-43fb-9dff-d4eaccc52512.mov
https://user-images.githubusercontent.com/220893/225091552-37426048-bbc7-4372-bfee-ea6229cdb747.mov
=> PHC-4075 - Update navigation header

example/reactotron.ts, src/components/tiles/Tile.tsx, src/hooks/useAsyncStorage.ts
- Use unique key for Async Storage
- Update Reactotron config to display Async Storage
=> PHC-4075 - Use unique key for Async Storage

src/components/tiles/Tile.tsx
- Remove circular dependency warning in Tile component
=> PHC-4075 - Remove circular dependency warning in Tile component

src/screens/ProfileScreen.tsx
- Update Profile screen with theme
=> PHC-4075 - Add theme/style to profile screen

example/storybook/stories/TrackTile/AdvancedTrackerEditor.stories.tsx, package.json, src/components/TrackTile/ManageTrackers/ManageTrackers.test.tsx, src/components/TrackTile/PillarsTile/PillarsTile.test.tsx, src/components/TrackTile/TrackTile.test.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.test.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.test.tsx, src/components/TrackTile/TrackerDetails/UnitPicker.test.tsx, src/components/TrackTile/TrackerDetails/UnitPicker.tsx, src/components/TrackTile/hooks/test/useTrackerValues.test.ts, src/components/TrackTile/hooks/useTrackers.ts, src/components/TrackTile/icons/Chevron.tsx, src/components/TrackTile/styles/compose-styles.ts, tsconfig.json, yarn.lock
- Added @testing-library/react-hooks
- Added types for d3-scale
- Switched to @react-native-picker/picker
- Updated to newer api in newer @testing-library
- Fixed various typing issues
=> PHC-4329 - Fix TypeScript build errors

jest.config.js, jest.setup.ts, src/components/TrackTile/TrackTile.test.tsx, src/components/TrackTile/TrackerDetails/UnitPicker.test.tsx, src/components/TrackTile/TrackerRow/TrackerRow.tsx, src/components/TrackTile/formatters/formatters.test.ts, src/components/TrackTile/hooks/test/useRecentCodedValues.test.ts, src/components/TrackTile/util/convert-value.test.ts
- Fix and enable 12 test files in components/TrackTile (still working on 5)
- Update mocking in jest.setup.ts
- Update @react-native-picker/picker mocking
=> PHC-4329 - Update TrackTile tests

src/hooks/useNotifications.test.tsx, src/hooks/useNotifications.tsx, src/navigators/NotificationsStack.tsx, src/navigators/TabNavigator.tsx, src/screens/NotificationsScreen.tsx
- Introduce the useNotifications hook
- Add Notifications Screen
- Storybook
- Increase test coverage
<div style={flex: 1; flex-direction="row" }>
</div>
=> PHC-4539 Add Notifications Screen

__mocks__/react-native-draggable-flatlist.tsx, __mocks__/svgMock.tsx, jest.config.js, jest.setup.ts, package.json, src/components/TrackTile/ManageTrackers/ManageTrackers.test.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.test.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/AdvancedTrackerEditor.test.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.test.tsx, yarn.lock
- Add some mocking and unmocking
- Downgrade d3-scale
=> PHC-4320 - Get more tests working

src/screens/NotificationsScreen.test.tsx, src/screens/NotificationsScreen.tsx
- Increase test coverage by adding tests for the notifications screen
=> PHC-4539: Add unit tests for notifications screen

src/components/tiles/Tile.tsx
- Switch default display mode to full length tiles
=> Default Tile to fullLength

lib/i18n/index.ts, package.json, yarn.lock
- Add intl-pluralrules polyfill, removing the error shown below
=> chore: Add intl-pluralrules polyfill

example/storybook/stories/Wearables/SelectorRow.stories.tsx, example/storybook/stories/Wearables/SelectorView.stories.tsx, example/storybook/stories/Wearables/SwitchRow.stories.tsx, example/storybook/stories/Wearables/SyncTypeSelectionRow.stories.tsx, example/storybook/stories/Wearables/SyncTypeSelectionView.stories.tsx, example/storybook/stories/Wearables/WearableRow.stories.tsx, example/storybook/stories/Wearables/WearablesView.stories.tsx
- Quick fix to resolve storybook path issues, defaultStyles are still merged with the empty styles passed in
=> Fix wearable storybook imports

bin/scripts/copyAdditionalFiles, package.json
- Icon files were not being copied over, extract copy logic to script so it can scale
=> fix: Copy icon files

src/components/TrackTile/TrackerDetails/to-fhir-resource.ts, src/components/TrackTile/TrackerDetails/to-observation-resource.test.ts, src/components/TrackTile/TrackerDetails/to-observation-resource.ts, src/components/TrackTile/TrackerDetails/to-procedure-resource.test.ts, src/components/TrackTile/TrackerDetails/to-procedure-resource.ts, src/components/TrackTile/hooks/test/useAxiosTrackTileService.test.ts, src/components/TrackTile/hooks/useAxiosTrackTileService.ts, src/components/TrackTile/services/TrackTileService.ts
- Use individual account and project attributes
=> chore: Use individual account attributes

example/storybook/stories/index.ts, src/components/TrackTile/hooks/test/useAxiosTrackTileService.test.ts, src/components/TrackTile/hooks/useAxiosTrackTileService.ts
-  Add `v1` to the endpoints for TrackTiles
=> chore: Use correct endpoints

example/reactotron.ts
- In the example app and behind `__DEV__` (only), patch console.log so that it outputs to Reactotron as well
=> chore: Add console logging to reactotron

src/components/tiles/TilesList.tsx, src/navigators/HomeStack.tsx, src/screens/TrackTileSettingsScreen.tsx
=> chore: Add TrackTile settings

src/common/DeveloperConfig.ts, src/common/RootProviders.tsx, src/components/DeveloperConfigProvider.test.tsx, src/navigators/HomeStack.tsx
- Allow providing a custom base URL to enable working against non-production environments.
=> feat: Allow providing a custom base URL

example/storybook/stories/TrackTile/TrackTiles.stories.tsx, example/storybook/stories/TrackTile/util/MockEnvironmentDecorator.tsx, src/components/TrackTile/TrackerRow/TrackerRow.test.tsx, src/components/TrackTile/TrackerRow/TrackerRow.tsx, src/components/TrackTile/util/convert-value.test.ts, src/components/TrackTile/util/convert-value.ts
- Fixed issue where missing value was converted to NaN
- Added safe guards in convert function to assume 0 if value is undefined
- Updated `MockEnvironmentDecorator` to use the mocked axios instance for stories
=> fix: PHC-4644 Fix Track Tile Tracker NaNs

example/storybook/stories/TrackTile/Tracker.stories.tsx, src/components/TrackTile/TrackerRow/RadialProgress.tsx, src/components/TrackTile/TrackerRow/Tracker.tsx, src/components/TrackTile/TrackerRow/TrackerRow.tsx
=> PHC-5429 - Update Tracker style - checkpoint #2

src/components/tiles/TilesList.tsx, src/navigators/HomeStack.tsx, src/screens/TrackTileAdvancedDetailsScreen.tsx, src/screens/TrackTileAdvancedEditorScreen.tsx
-  Add PillarsTile to TileList
Coming in next PR
=> PHC-5429 - Add PillarsTile to TileList

README.md, example/AppDemo.tsx, example/storybook/stories/ActivityIndicatorView.stories.tsx, example/storybook/stories/index.ts, src/common/DeveloperConfig.ts, src/components/ActivityIndicatorView.tsx, src/components/DeveloperConfigProvider.test.tsx, src/components/DeveloperConfigProvider.tsx
- Updated ActivityIndicatorView to use the primaryColor
- Removed `accentColor` as an initial property as this is derived from `primaryColor` (a lighter version)
https://user-images.githubusercontent.com/220893/234351256-4ce18eb6-d941-44fe-b5f0-a4eea8ec8d14.mov
=> feat: Update ActivityIndicatorView w/ primaryColor

.prettierignore, src/navigators/RootStack.tsx, tsconfig.json
=> Hide header on LoginScreen

package.json, src/components/TrackTile/icons/indicator/index.tsx, yarn.lock
https://user-images.githubusercontent.com/1445395/234660907-ff3e6e6e-c105-43c6-bbde-67b12a41dec4.mov
=> feat: Upgrade chromicons for several new icons

src/components/Wearables/WearableLifecycleProvider.test.tsx, src/components/Wearables/WearableLifecycleProvider.tsx, src/components/Wearables/WearablesView.test.tsx, src/components/Wearables/WearablesView.tsx, src/screens/WearablesScreen.tsx
- Removes the enableMultiWearable logic
=> chore: PHC-4574 Remove enableMultiWearable Logic

src/components/AppNavHeader.tsx, src/components/TrackTile/PillarsTile/PillarsTile.tsx, src/components/TrackTile/TrackTile.tsx, src/components/tiles/Tile.tsx, src/components/tiles/TilesList.tsx, src/navigators/TabNavigator.tsx, src/screens/HomeScreen.tsx
- Update spacing with and without TrackTile
- Apply most important surface style updates from [upstream feature PR](https://github.com/lifeomic/react-native-sdk/pull/162)
https://user-images.githubusercontent.com/220893/235231705-771e8b55-419e-48d6-bd98-677198a944af.mov
https://user-images.githubusercontent.com/220893/235231716-2211a82d-e056-4609-862c-fc9af5afd337.mov
=> feat: Update spacing and most important style changes

src/screens/LoginScreen.tsx
=> fix: Use correct path

example/storybook/stories/Wearables/WearablesView.stories.tsx
=> test: Fix wearable story

src/components/BrandConfigProvider/theme/base/default.ts, src/components/BrandConfigProvider/theme/generateColors.ts, src/components/TrackTile/TrackerDetails/TrackerHistoryChart/TrackerHistoryChart.tsx, src/components/TrackTile/TrackerRow/Tracker.tsx, src/components/tiles/Tile.tsx
- Add `primarySource` color to be the fixed reference to the original brand source color
=> PHC-4621 - Add primarySource color

src/components/Circles/Post.tsx, src/components/Circles/PostsList.tsx, src/components/tiles/TilesList.tsx, src/hooks/useAppConfig.ts, src/hooks/useGraphQLClient.test.tsx, src/hooks/useGraphQLClient.tsx, src/hooks/useJoinCircles.tsx, src/hooks/useNotifications.test.tsx, src/hooks/usePosts.tsx, src/navigators/HomeStack.tsx, src/navigators/types.tsx, src/screens/HomeScreen.test.tsx, src/screens/HomeScreen.tsx, src/screens/NotificationsScreen.test.tsx, src/screens/PostsScreen.tsx
- Fix baseURL issue with the GraphQL client (first commit)
- Adds hook to auto-join available circles
- Adds a very basic circle discussion screen, text only (no reactions, no replies, no media)
- Add loading indicator for the loading scrollView
- Apply any feedback from this PR
- Add unit tests
- Possible renaming of components/hooks for consistency
- Identify cause of warnings shown in video
https://user-images.githubusercontent.com/76954025/235528416-782c794c-2710-4ef4-8bcc-e2483463bb55.mp4
=> PHC-4753 Add circle discussions screen

example/package.json, package.json
- Move @material/material-color-utilities to peerDependencies
=> feat: Move material utilities to peerDependencies

src/components/tiles/TilesList.tsx
- Images were being rendered with a height of 0 so they were not being displayed
=> Add default style to tile icons

src/components/BrandConfigProvider/styles/createStyles.ts, src/components/Circles/Post.test.tsx, src/components/Circles/Post.tsx, src/components/Circles/PostList.test.tsx, src/components/Circles/PostsList.tsx, src/components/tiles/TilesList.tsx, src/hooks/useInfinitePosts.test.tsx, src/hooks/useInfinitePosts.tsx, src/hooks/useJoinCircles.test.tsx, src/hooks/usePosts.tsx, src/navigators/HomeStack.tsx, src/navigators/types.tsx, src/screens/CircleDiscussionScreen.tsx
- Adds loading indicator when paging down
- Moves circle tiles below app tiles
- Uses button text for circle name if available otherwise defaults to circle name
- Adds new `Any` style naming option
- Adds unit tests
- Adds default icon for circle tiles
- Some renames and general cleanup
<div style={{flex: 1, flex-direction: 'row' }}>
</div>
<div style={{flex: 1, flex-direction: 'row' }}>
</div>
=> PHC-4753 Circle Discussions cleanup and tests

src/components/Circles/EmptyComments.tsx, src/components/Circles/PostUnavailable.tsx, src/components/Circles/ThreadComment.tsx, src/components/Circles/ThreadPost.tsx
=> PHC-4775 Add Missing Thread i18n Strings

example/yarn.lock, src/components/TrackTile/PillarsTile/PillarsTile.tsx, src/components/TrackTile/TrackTile.tsx
- Update Pillar margins
- Update TrackTile background and margins
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/220893/235792772-5f39e1c1-521f-46e0-bbf8-eaa17bbadf49.png) | ![image](https://user-images.githubusercontent.com/220893/235792565-34792156-5c94-42de-9df5-a318ac244c17.png) |
=> fix: Update margins and background

src/screens/AuthedAppTileScreen.test.tsx, src/screens/AuthedAppTileScreen.tsx
- Passes the PatientId to the Authed App Tile
=> fix: Add PatientId to Authed App Tiles

jest.setup.ts, src/components/Circles/Thread.tsx, src/components/Circles/__tests__/EmptyComments.test.tsx, src/components/Circles/__tests__/Post.test.tsx, src/components/Circles/__tests__/PostList.test.tsx, src/components/Circles/__tests__/PostUnavailable.test.tsx, src/components/Circles/__tests__/ReactionsToolbar.test.tsx, src/components/Circles/__tests__/Thread.test.tsx, src/components/Circles/__tests__/ThreadComment.test.tsx, src/components/Circles/__tests__/ThreadPost.test.tsx, src/components/Circles/__tests__/initials.test.ts, src/components/Circles/initials.tsx, src/hooks/usePost.test.tsx
- Adds tests for the thread components
- Moves other circle tests into a `__tests__` folder
- fixes a couple of bugs
=> PHC-4775 Add Unit Tests for Post Details

src/components/Circles/ThreadComment.tsx, src/components/Circles/ThreadPost.tsx, src/components/Circles/__tests__/Thread.test.tsx, src/components/Circles/__tests__/ThreadComment.test.tsx, src/components/Circles/__tests__/ThreadPost.test.tsx, src/hooks/useInfinitePosts.tsx, src/hooks/usePost.ts
- Adds the Reaction Toolbar to post and comment
=> PHC-4775 Add Thread Reactions

.eslintrc.js, example/src/screens/FhirExampleScreen.tsx, example/storybook/stories/ActivityIndicatorView.stories.tsx, example/storybook/stories/BrandConfigProvider/BrandConfigProvider.stories.tsx, example/storybook/stories/BrandConfigProvider/ExampleBox.tsx, example/storybook/stories/BrandConfigProvider/ThemeExampleScreen.tsx, example/storybook/stories/CustomAppTileScreen.stories.tsx, example/storybook/stories/ExampleApp.stories.tsx, example/storybook/stories/OAuth.stories.tsx, example/storybook/stories/TrackTile/AdvancedTrackerDetails.stories.tsx, example/storybook/stories/TrackTile/AdvancedTrackerEditor.stories.tsx, example/storybook/stories/TrackTile/ManageTrackers.stories.tsx, example/storybook/stories/TrackTile/Pillar.stories.tsx, example/storybook/stories/TrackTile/PillarsTile.stories.tsx, example/storybook/stories/TrackTile/TrackTiles.stories.tsx, example/storybook/stories/TrackTile/Tracker.stories.tsx, example/storybook/stories/TrackTile/TrackerDetails.stories.tsx, example/storybook/stories/TrackTile/TrackerHistoryChart.stories.tsx, example/storybook/stories/TrackTile/util/MockEnvironmentDecorator.tsx, src/components/Circles/__tests__/ThreadComment.test.tsx, src/components/Circles/__tests__/ThreadPost.test.tsx, src/navigators/TabNavigator.tsx
- No more direct imports from src = no more breaking the starter app
- Enforced by CI
=> fix: Enforce no imports from src

__mocks__/react-native-paper.ts, example/storybook/stories/TrackTile/util/MockEnvironmentDecorator.tsx, src/components/AppNavHeader.tsx, src/components/Circles/Post.tsx, src/components/Circles/PostsList.tsx, src/components/Circles/Thread.tsx, src/components/Circles/__tests__/CreateEditPostModal.test.tsx, src/components/Circles/__tests__/Post.test.tsx, src/components/Circles/__tests__/PostList.test.tsx, src/components/Circles/__tests__/Thread.test.tsx, src/hooks/usePost.test.tsx, src/hooks/usePosts.tsx, src/navigators/HomeStack.tsx, src/navigators/types.tsx, src/screens/CircleDiscussionScreen.tsx, src/screens/CircleThreadScreen.tsx
- Wires up the discussion screen to open the thread screen when pressed
- Fixes a path issue
- Fixes the back arrow for the header (no more X)
https://github.com/lifeomic/react-native-sdk/assets/2295908/f2ec383a-6b53-42fe-8c78-629661ff9d5c
=> feat: PHC-4775 Add Open Thread Screen Logic

src/components/Circles/CreateEditPostModal.tsx, src/components/Circles/PostsList.tsx, src/components/Circles/Thread.tsx, src/components/Circles/ThreadComment.tsx, src/components/Circles/__tests__/CreateEditPostModal.test.tsx, src/components/Circles/__tests__/Thread.test.tsx, src/components/Circles/__tests__/ThreadComment.test.tsx, src/hooks/useCreatePost.test.tsx, src/hooks/usePosts.tsx, src/hooks/useReactionMutations.test.tsx, src/hooks/useReactionMutations.tsx, src/hooks/utils/optimisticallyUpdatePosts.ts, src/screens/CircleThreadScreen.tsx
- Add Replying to posts and comments from the thread screen
- Adds opening a thread from inside a thread
- Adds autofocus to the new comment/post
https://github.com/lifeomic/react-native-sdk/assets/2295908/5e4f4cc8-8fee-45fa-8797-261ac5dd3fc1
Fix for the comment not loading which is visible in the previous video
https://github.com/lifeomic/react-native-sdk/assets/2295908/9aa089c4-4097-48c4-af44-4343e81d0761
=> feat: PHC-4775 Add Thread Replying and Nested Thread Opening

lib/i18n/locales/en.json, src/components/Circles/Thread.tsx, src/components/Circles/ThreadComment.tsx, src/components/Circles/__tests__/Thread.test.tsx, src/hooks/useLoadReplies.test.tsx, src/hooks/usePosts.tsx
- Adds ability to load in previous replies
https://github.com/lifeomic/react-native-sdk/assets/2295908/298e4a9e-adaa-4db2-aabc-50a1e37ec789
=> chore: PHC-4775 Add Comment Loading

example/storybook/stories/TrackTile/util/MockEnvironmentDecorator.tsx, src/hooks/index.ts, src/hooks/useAppConfig.ts, src/hooks/useExchangeToken.test.tsx, src/hooks/useExchangeToken.tsx, src/hooks/useHandleAppTileEvents.test.ts, src/hooks/useHandleAppTileEvents.ts, src/navigators/TabNavigator.tsx, src/navigators/types.tsx, src/screens/AuthedAppTileScreen.test.tsx, src/screens/AuthedAppTileScreen.tsx
https://github.com/lifeomic/react-native-sdk/assets/19395435/872c656c-2690-4aa3-abba-ea5fdac19061
=> feat: Surveys + opening urls support

example/AppDemo.tsx, example/android/app/build.gradle, example/ios/example.xcodeproj/project.pbxproj, example/package.json, example/yarn.lock, src/common/DeveloperConfig.ts, src/navigators/TabNavigator.tsx, src/screens/NotificationsScreen.tsx
- Remove material icons requirement
- Replaced main tab navigation menu (including example additional tab) with chromicons
- Replaced Notification icons with chromicons (note that these aren't exactly the same but I think fit a bit better)
| Before | After |
|-|-|
|![Simulator Screen Shot - iPhone 14 - 2023-05-17 at 15 17 22](https://github.com/lifeomic/react-native-sdk/assets/220893/402ee67d-054e-4ac0-96fd-afca74e827cb)|![Simulator Screen Shot - iPhone 14 - 2023-05-17 at 16 00 11](https://github.com/lifeomic/react-native-sdk/assets/220893/29c9bc5a-9d70-4db4-bf45-b4706394808c)|
| Before | After |
|-|-|
|![Simulator Screen Shot - iPhone 14 - 2023-05-17 at 15 21 17](https://github.com/lifeomic/react-native-sdk/assets/220893/7b7c6f31-8f66-40a8-a7be-641879af9b8e) |![Simulator Screen Shot - …
=> PHC-4573 - Remove material icons

src/hooks/Circles/types.ts, src/hooks/Circles/useCreatePost.ts, src/hooks/Circles/useInfinitePosts.tsx, src/hooks/Circles/useLoadReplies.ts, src/hooks/Circles/useReactionMutations.tsx, src/hooks/Circles/useUpdatePostMessage.ts, src/hooks/Circles/utils/optimisticallyDeletePosts.ts, src/hooks/Circles/utils/optimisticallyUpdatePosts.ts
- Fixes issues when modifying nested replies
=> Recursively update all cached posts

example/storybook/stories/OAuth.stories.tsx, src/common/RootProviders.tsx, src/components/Invitations/InviteNotifier.test.ts, src/components/Invitations/InviteNotifier.ts, src/components/Invitations/InviteProvider.test.tsx, src/components/Invitations/InviteProvider.tsx, src/hooks/useAcceptInviteMutation.ts, src/hooks/useActiveAccount.test.tsx, src/hooks/useActiveAccount.tsx, src/hooks/useAuth.tsx, src/hooks/useOAuthFlow.tsx, src/hooks/usePendingInvite.tsx, src/index.ts, src/types.ts
Will be sharing a demo video privately here in a bit.
=> feat: Add support for emitting invite params and accepting invite

example/storybook/stories/ExampleApp.stories.tsx, src/common/DeveloperConfig.ts, src/components/BrandConfigProvider/index.ts, src/navigators/HomeStack.tsx, src/navigators/NotificationsStack.tsx, src/navigators/SettingsStack.tsx
- Add the ability to specifiy a custom AppNavHeader
| | | |
|-|-|-|
|![image](https://github.com/lifeomic/react-native-sdk/assets/220893/8ff4aec2-87be-4a4f-a750-f31bff0480f4) | ![image](https://github.com/lifeomic/react-native-sdk/assets/220893/855124b5-a17e-4b62-8d4d-c48737bc9453) |  ![image](https://github.com/lifeomic/react-native-sdk/assets/220893/379cd8e9-910a-45ae-bbd8-8531b8343695) |
=> feat: Add custom AppNavHeader

example/storybook/stories/Wearables/WearableRow.stories.tsx, lib/i18n/locales/en.json, src/components/Wearables/ToggleButton.tsx, src/components/Wearables/WearableLifecycleProvider.test.tsx, src/components/Wearables/WearableLifecycleProvider.tsx, src/components/Wearables/WearableRow.test.tsx, src/components/Wearables/WearableRow.tsx, src/components/Wearables/WearableTypes.ts, src/components/Wearables/WearablesView.tsx, src/hooks/useFeature.test.tsx, src/hooks/useFeature.ts, src/hooks/useWearableBackfill.test.tsx, src/hooks/useWearableBackfill.tsx, src/screens/WearablesScreen.tsx
- Adds a backfill button to the wearable row when the feature is enabled
- Adds an onBackfill lifecycle handler hook
- Fixes typo in fitbit auth text
- Adds a loading indicator to the ToggleButton
https://github.com/lifeomic/react-native-sdk/assets/2295908/5769e23e-c7f8-4f93-8438-39e36eff9ff0
=> Add Wearable Backfill

.eslintignore, .eslintrc.js, example/storybook/stories/Wearables/SwitchRow.stories.tsx, example/storybook/stories/Wearables/WearableRow.stories.tsx, src/components/TrackTile/ManageTrackers/ManageTrackers.tsx, src/components/TrackTile/ManageTrackers/useSyncTrackerOrder.ts, src/components/TrackTile/PillarsTile/Pillar.tsx, src/components/TrackTile/TrackTile.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/AdvancedTrackerEditor.test.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/AdvancedTrackerEditor.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/CodingCategoryPicker.tsx, src/components/TrackTile/TrackerDetails/TrackAmountControl.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.tsx, src/components/TrackTile/TrackerDetails/TrackerHistoryChart/Bar.tsx, src/components/TrackTile/TrackerDetails/TrackerHistoryChart/TrackerHistoryChart.tsx, src/components/TrackTile/TrackerDetails/UnitPicker.tsx, src/components/TrackTile/TrackerRow/RadialProgress.tsx, src/components/TrackTile/hooks/useFlattenedStyles.ts, src/components/TrackTile/hooks/useRecentCodedValues.ts, src/components/TrackTile/hooks/useTrackerValues.ts, src/components/TrackTile/hooks/useTrackers.ts, src/components/TrackTile/util/darken-hex-color.ts, src/components/TrackTile/util/is-code-equal.ts, src/components/Wearables/SelectorRow.tsx, src/components/Wearables/WearableLifecycleProvider.tsx, src/components/Wearables/WearableRow.tsx
- Superficial changes to satisfy the linter
=> chore: Enable lint for TrackTile

.eslintrc.js, src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.tsx, src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/AdvancedTrackerEditor.tsx
- Do not render components inline
=> chore: More lint fixes

src/components/TrackTile/ManageTrackers/ManageTrackers.tsx, src/components/TrackTile/TrackerDetails/TrackAmountControl.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.test.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.tsx, src/components/TrackTile/hooks/useTrackers.ts
- Fixes bouncing of tracker amounts when adding/subtracting
- Restores original logic in ManageTrackers where useTrackers is conditionally rendered depending on if trackerRequestMeta is provided.
=> PHC-4837 Tracker fixes

src/navigators/TabBar.tsx
- Update named styles for the TabBar to align with new named styles requirements
=> fix: Update named styles for TabBar

src/components/TrackTile/TrackerDetails/NumberPicker.tsx
- Fixes bug/typo when creating valid target ranges
N/A
=> fix: Fix number picker range bug

src/components/Circles/PostsList.tsx
- Fixes bug where the view might not stretch to fit the entire screen depending on content/actions
=> fix: Set view height so it always uses 100%

example/package.json, example/storybook/helpers/DataProviderDecorator.tsx, example/storybook/stories/MyData/LineChart.stories.tsx, example/storybook/stories/MyData/index.ts, example/storybook/stories/index.ts, example/yarn.lock, jest.config.js, package.json, src/components/MyData/LineChart/Title.tsx, src/components/MyData/LineChart/TraceLine.tsx, src/components/MyData/LineChart/index.test.tsx, src/components/MyData/LineChart/index.tsx, src/components/MyData/useVictoryTheme.ts, src/hooks/useActiveAccount.tsx, src/hooks/useActiveProject.tsx, src/hooks/useFhirClient.test.tsx, src/hooks/useFhirClient.tsx, yarn.lock
- Adds a basic chart component that supports 1 or 2 traces for a given date range
https://github.com/lifeomic/react-native-sdk/assets/2295908/c3a1d359-e32b-4918-b508-b2122a5cdf2f
=> fix: PHC-4968 Add My Data Line Chart Component

example/storybook/helpers/SafeView.tsx, example/storybook/stories/MyData/MyData.stories.tsx, example/storybook/stories/MyData/index.ts, src/components/MyData/LineChart/TraceLine.tsx, src/components/MyData/LineChart/index.tsx, src/components/MyData/useCommonChartProps.tsx, src/hooks/useAppConfig.ts, src/screens/MyDataScreen.test.tsx, src/screens/MyDataScreen.tsx
- Adds the my data screen for displaying multiple line charts
https://github.com/lifeomic/react-native-sdk/assets/2295908/126fb0c5-57ad-4400-a961-ee6a5f27caec
=> PHC-4969 Create My Data Screen

src/components/MyData/LineChart/DataSelector.tsx, src/components/MyData/LineChart/TraceLine.tsx, src/components/MyData/LineChart/index.test.tsx, src/components/MyData/LineChart/index.tsx, src/components/MyData/LineChart/useChartData.test.ts, src/components/MyData/LineChart/useChartData.ts, src/hooks/useFhirClient.tsx
- Adds the ability to select data points to see the value within the chart
- Fixes some domain related issues where data did not match the x axis
https://github.com/lifeomic/react-native-sdk/assets/2295908/af8875d9-4652-43f8-99be-b040da43168b
=> fix: PHC-4968 Add Chart Data Selection

README.md, example/android/app/build.gradle, example/android/app/src/main/java/com/example/MainApplication.java, example/android/build.gradle, example/android/gradle.properties, example/android/settings.gradle, example/package.json, example/yarn.lock
- update readme
- conditionalize initialization of firebase and react native notifications in gradle build files
- conditionalize initialization of firebase init in MainApplication.java
n/a
=> fix: Fix Android app crashes due to Firebase init

example/storybook/stories/MyData/LineChart.stories.tsx, example/storybook/stories/MyData/MyData.stories.tsx, src/components/MyData/LineChart/TraceLine.tsx, src/components/MyData/LineChart/index.test.tsx, src/components/MyData/LineChart/useChartData.test.ts, src/components/MyData/LineChart/useChartData.ts, src/screens/MyDataScreen.test.tsx
- Codes are now provided as an array to allow searching for multiple codes at the same time (e.g. Garmin Steps or Fitbit Steps)
=> fix: PHC-4968 Add Multi Code Trace Support

README.md, src/common/DeveloperConfig.ts, src/screens/LoginScreen.test.tsx, src/screens/LoginScreen.tsx
This PR adds the ability to customize the login screen.
https://github.com/lifeomic/react-native-sdk/assets/19395435/2cf87ef1-c76d-40b6-8ee6-10e92905d885
=> feat: Customize the login screen

README.md, example/android/app/build.gradle, example/android/app/google-services.json, example/android/app/src/main/java/com/example/MainApplication.java, example/android/build.gradle, example/android/gradle.properties, example/android/settings.gradle
- google-services.json file
- condense README.md directions 
- revert initial approach of excluding react-native-notifications (which initializes firebase)
n/a
=> Fix: android example app crashes due to firebase init

example/storybook/stories/MyData/LineChart.stories.tsx, src/components/MyData/LineChart/AxisArrows.tsx, src/components/MyData/LineChart/DataSelector.tsx, src/components/MyData/LineChart/index.test.tsx, src/components/MyData/LineChart/index.tsx, src/components/MyData/useCommonChartProps.tsx, src/screens/MyDataScreen.tsx
- Reworked the data selection to use absolutely positioned TouchableWithoutFeedback for data selection. SVG onPress wasn't working on iOS on a real device
- Switched the date range format because creating a new array was causing selection to be dropped on rerender
https://github.com/lifeomic/react-native-sdk/assets/2295908/e5ed1cc9-9046-401e-8eae-cf792e07ec4d
=> fix: PHC-4968 Fix Data Selection on Device

src/hooks/useFhirClient.test.tsx, src/hooks/useFhirClient.tsx
Add support for upserting a FHIR resource bundle.
=> feat: Add Bundle support

src/hooks/useOAuthFlow.tsx
=> fix: Fix token revocation

README.md
- Adds clarity on file type for iOS
- Fixes a typo in the Android setup code
=> chore: Fix Splash Screen ReadME wording

src/hooks/useHandleAppTileEvents.test.ts, src/hooks/useHandleAppTileEvents.ts, src/navigators/HomeStack.tsx, src/navigators/types.tsx, src/screens/YoutubePlayerScreen.test.tsx, src/screens/YoutubePlayerScreen.tsx
https://github.com/lifeomic/react-native-sdk/assets/19395435/2af02cfa-c233-4392-83d6-df15048162cf
=> feat: Youtube video player

src/hooks/Circles/types.ts
Fixes profile images not loading in circles
=> fix: Profile images not loaded in circles

src/components/Circles/AvatarIcon.tsx, src/components/Circles/PostItem.tsx, src/components/Circles/ProfileImage.tsx, src/components/Circles/ThreadComment.tsx, src/components/Circles/__tests__/ProfileImage.test.tsx
- Adds placeholders for when an author's profile information is not available on the post data
- Uses theme title styles for a post author's name
=> chore: use defaults when without profile info

src/components/AppNavHeader.tsx
Respect some header navigation options in our custom navigation header:
- headerTitle: Override title with either a title string or components
- headerLeft: Inject buttons/etc into the header in the left position
- headerRight: Inject buttons/etc into the header in the right position
- headerShown: Hide the header as needed
https://github.com/lifeomic/react-native-sdk/assets/76954025/cbfe1c0b-1fbc-47b0-85f9-34983c6476a0
=> chore: Use navigation options to modify header

README.md, example/ios/example/RNTLaunchScreen.m
- Fixes the issue where the launch screen was displayed off screen on iOS
=> fix: Fix RNTLaunchScreen Resizing and Update Section in README

example/storybook/stories/SharingRenderers/PointBreakdown.stories.tsx, src/components/SocialShare/index.ts, src/components/index.ts
- Exports the Social Share Component and pointBreakDown functions from the main module
=> fix: Export Social Share Components

src/screens/ConsentScreen.test.tsx, src/screens/ConsentScreen.tsx
I tried to add checkboxes, but I kept getting errors about missing fonts. I can look at that separately.
**Before:**
**After:**
=> Support multiple consent acceptance items

src/common/DeveloperConfig.ts, src/navigators/TabNavigator.tsx
=> feat: Allow overriding of default tabs

example/storybook/stories/CustomScreenInjection/CustomScreenInjection.stories.tsx, example/storybook/stories/ExampleApp/ExampleApp.stories.tsx, src/common/DeveloperConfig.ts, src/navigators/TabBar.tsx, src/navigators/TabNavigator.tsx
Consolidates all tab bar related config into a single spot and allows for a more dynamic way to compose tabs.
=> Consolidate tab developerConfig settings

example/storybook/stories/TrackTile/TrackerDetails.stories.tsx, src/common/DeveloperConfig.ts, src/components/TrackTile/TrackerDetails/TrackerDetails.tsx
- Add image and color configuration overrides for individual trackers
- Add radialProgressRotation configuration
=> PHC-5145 - Add image and color configuration overrides for individual trackers

example/storybook/stories/TrackTile/TrackerDetails.stories.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.tsx, src/components/TrackTile/TrackerRow/RadialProgress.tsx
- Use defaultStyles settings for svg
- Use tracker api for color and image
=> PHC-5145 - Update TrackerDetails to use theme and tracker api

README.md, package.json
- Update package.json scripts to copy build to custom project
=> docs: Add yarn script to copy build to custom project

src/hooks/Circles/usePrivatePosts.ts, src/screens/DirectMessagesScreen.tsx
Add style hooks to messages screen
=> chore: Messages can be themed

README.md, UPGRADING.md
Adding an explicit UPGRADING.md, which can be used to provide explicit guidance for how to go between major versions.
First entry: guidance for upgrading in response to #338.
=> docs: add documentation for upgrading between major versions

jest.config.js, package.json, src/hooks/rest-api.tsx, src/test-utils/rest-api-mocking.ts, src/types/rest-types.ts, yarn.lock
This PR proposes the foundational files for using `one-query` in this project. This PR is intimately tied to its followup, which actually _uses_ one-query for the first time: #342.
Overall, I think that using one-query will _really_ help to:
- _Reduce boilerplate_ required for integrating with new API endpoints (you _only_ need to update the master type definition to integrate with a new endpoint)
- _Encourage consistency_ in API interaction. All API calls go through the same flow, and are defined + implemented the same way.
Both of these wins contribute to delivering the big one: _help us move faster_ 😄
See #342 for a demo video showcasing the developer experience of using the new utilities.
=> chore: add core one-query integration

UPGRADING.md
Adding upgrading guidance in response to #342.
=> docs: add upgrade guide for 2.x -> 3.x

src/screens/MessageScreen.tsx
Per feedback in the last PR memoize the userList array function.
=> fix: Memo userList

src/common/RefreshNotifier.tsx, src/components/HeaderLeftRefreshButton.tsx, src/components/TrackTile/hooks/test/useAxiosTrackTileService.test.ts, src/components/TrackTile/hooks/test/useTrackerValues.test.ts, src/components/TrackTile/hooks/useAxiosTrackTileService.ts, src/components/TrackTile/hooks/useTrackerValues.ts, src/hooks/useAppConfig.ts, src/screens/HomeScreen.test.tsx, src/screens/HomeScreen.tsx
https://github.com/lifeomic/react-native-sdk/assets/1445395/d0e562f7-496e-4d7a-aeb3-eb6d21ed2e37
=> feat: allow for optional HomeScreen refresh button

src/screens/MessageScreen.tsx
- Use the initials of the recipient when no avatar
- Don't show chat in message screen for current user
=> PHC-5294 - Use initials when no avatar

README.md
=> fix: trigger a release

src/components/TodayBadge.test.tsx, src/components/TodayBadge.tsx, src/components/tiles/Tile.tsx, src/components/tiles/TilesList.test.tsx, src/components/tiles/TilesList.tsx, src/hooks/todayTile/types.ts, src/hooks/todayTile/useTodayTasks.test.tsx, src/hooks/todayTile/useTodayTasks.tsx, src/types/rest-types.ts
- Add Badge to TodayTile to display assigned surveys or consents that require action
=> feat: Add TodayTile badge

src/hooks/useActiveAccount.test.tsx, src/hooks/useActiveAccount.tsx, src/hooks/useActiveProject.test.tsx, src/hooks/useActiveProject.tsx, src/hooks/useAsyncStorage.tsx, src/hooks/useNotificationManager.test.tsx, src/hooks/useNotificationManager.tsx, src/hooks/useOnboardingCourse.test.tsx, src/hooks/useOnboardingCourse.tsx, src/navigators/LoggedInStack.tsx
- Default storage value to a third state (undefined) so others can detect when a value has been retrieved or not.
- Consolidate ActivityIndicators
- Bring back useJoinCircles()
=> Improve Loading #4: Add back in loading flag for AsyncStorage

src/hooks/useActiveProject.tsx, src/hooks/useMe.ts, src/screens/LoginScreen.test.tsx, src/screens/LoginScreen.tsx
- The default "Login" button now shows the text "Accept Invite" when the app is opened with an invite
- When an invite is accepted and the user is already signed in and waiting at the Invite Required screen they are now correctly navigated to the next screen (Consent or Home).
=> Improve invite accept handling

example/android/app/src/main/java/com/example/RNTLaunchScreen.java, src/components/TrackTile/ManageTrackers/ManageTrackerRow.tsx, src/components/TrackTile/ManageTrackers/ManageTrackers.test.tsx, src/components/TrackTile/ManageTrackers/ManageTrackers.tsx, src/components/TrackTile/ManageTrackers/useSyncTrackerOrder.ts, src/components/TrackTile/TrackTile.test.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.test.tsx, src/components/TrackTile/TrackerDetails/useSyncTrackerSettingsEffect.tsx, src/components/TrackTile/TrackerRow/Tracker.tsx, src/components/TrackTile/TrackerRow/TrackerRow.test.tsx, src/components/TrackTile/TrackerRow/TrackerRow.tsx, src/components/TrackTile/hooks/test/useAxiosTrackTileService.test.tsx, src/components/TrackTile/hooks/test/useTrackers.test.ts, src/components/TrackTile/hooks/useAxiosTrackTileService.ts, src/components/TrackTile/hooks/useTrackers.ts, src/components/TrackTile/services/TrackTileService.ts, src/hooks/useAppConfig.tsx, src/screens/TrackTileSettingsScreen.test.tsx, src/screens/TrackTileSettingsScreen.tsx
- Updates the tracker settings screen to allow reordering and toggling of all items
- reworks the installed logic to be based off of a new field added to the tracker install settings so that a user can remove a installed flag if desired
https://github.com/lifeomic/react-native-sdk/assets/2295908/3bab3bfe-b5ab-4a85-9b8c-57ba51db8816
=> feat: Update Tracker Settings Editor

bin/scripts/syncWithProject.js, package.json, src/components/Invitations/InviteProvider.tsx, src/hooks/useActiveAccount.tsx, src/hooks/useActiveProject.tsx, src/hooks/useAppConfig.test.tsx, src/hooks/useAppConfig.tsx, src/hooks/useAuth.test.tsx, src/hooks/useAuth.tsx, src/hooks/useMe.ts, src/hooks/useSubjectProjects.tsx, yarn.lock
- Fixes invite flow when the user does not yet have an account
- Add script to watch for changes in SDK and build/copy to target project for easier development
=> Refresh session info with inviteId

example/storybook/stories/TrackTile/TrackTiles.stories.tsx, src/components/TrackTile/TrackTile.tsx
- Update conditional display of Card.Title
- Show it working with specific storys
https://github.com/lifeomic/react-native-sdk/assets/220893/7396dad9-e69a-45b0-9106-2f6790ab26f6
=> fix: Settings button without title

src/components/TrackTile/hooks/test/useAxiosTrackTileService.test.tsx, src/components/TrackTile/services/TrackTileService.ts
- Uses the latest capability version for track tiles
=> fix: Update Track Tile Capability Header to Version 3

README.md, src/common/DeveloperConfig.ts, src/components/DeveloperConfigProvider.test.tsx, src/navigators/LoggedInStack.tsx
This PR adds an `onAppSessionStart` hook that is triggered when a user signs in to the app. It can be used for analytics, check subscription status and navigate to a different page if a subscription is inactive, etc.
https://github.com/lifeomic/react-native-sdk/assets/19395435/3ab737f7-1a14-4f2d-9b45-a0942f48f112
=> onAppSessionStart hook

src/components/tiles/TilesList.test.tsx, src/components/tiles/TilesList.tsx, src/hooks/useAppConfig.tsx
=> feat: Render the app tiles title override

README.md, src/common/DeveloperConfig.ts
Side note: the previous npm publish failed. Using `feat` in this commit to trigger a new npm publish.
=> feat: Update the onAppSessionStart documtation

src/screens/AuthedAppTileScreen.test.tsx, src/screens/AuthedAppTileScreen.tsx
=> fix: Set the app tile title override as the screen title

example/storybook/stories/TrackTile/AdvancedTrackerDetails.stories.tsx, example/storybook/stories/TrackTile/AdvancedTrackerEditor.stories.tsx, example/storybook/stories/TrackTile/Indicator.stories.tsx, example/storybook/stories/TrackTile/ManageTrackers.stories.tsx, example/storybook/stories/TrackTile/Pillar.stories.tsx, example/storybook/stories/TrackTile/PillarsTile.stories.tsx, example/storybook/stories/TrackTile/TrackTiles.stories.tsx, example/storybook/stories/TrackTile/Tracker.stories.tsx, example/storybook/stories/TrackTile/TrackerDetails.stories.tsx, example/storybook/stories/TrackTile/TrackerHistoryChart.stories.tsx, example/storybook/stories/TrackTile/util/trackerData.ts
This PR improves TrackTile stories in preparation for some fixes [in the next PR](https://github.com/lifeomic/react-native-sdk/pull/380).
- Added namespacing to TrackTile stories
- Added non-pillar TrackTile examples with data
- Added story for TrackTile example in context with Pillars
=> PHC-5381-Brand-theme/style-fixes-related-to-tracker-settings-cog

src/common/DeveloperConfig.ts, src/screens/LoginScreen.tsx
- Allow overriding login screen button's text
=> Add ability to override login screen button text

src/components/tiles/Tile.tsx
=> Add style props for Tile component

src/hooks/useActivities.tsx
- Adds hook to fetch all activities
=> fix: Add activities hook

src/hooks/todayTile/useTodayTasks.tsx, src/hooks/useActivities.tsx
- Export survey responses hook and add input params
- Split Activity type from response type
=> Export survey responses hook

src/hooks/useMyMessages.tsx, src/screens/MessageScreen.test.tsx, src/screens/MessageScreen.tsx
=> Messages - Timestamps, sorting, new styles, preview prefix

src/screens/DirectMessagesScreen.test.tsx, src/screens/DirectMessagesScreen.tsx
https://github.com/lifeomic/react-native-sdk/assets/76954025/f033066d-392b-490e-a715-283857d8e8c6
=> Update styles for TextInput

src/hooks/useMe.test.tsx, src/hooks/useMe.ts, src/screens/ProfileScreen.test.tsx, src/screens/ProfileScreen.tsx
- Adding the full `subject` to the return value of `useMe`.
- Adding a `FhirProfileView` component which will look very similar to the `ProfileScreen` component, but be powered by FHIR data.
=> FLME-163: add FhirProfileView component

src/hooks/useMyMessages.tsx, src/screens/MessageScreen.tsx
This PR is almost only renames and code cleanup with the exception of tweaking the message timestamp abbreviations a bit.
=> Code cleanup/PR feedback for Messages

src/hooks/useActivities.tsx
This field was missing from the type.
=> fix: add deepLink field to activity type

src/types/rest-types.ts
Adding the Features API entry here.
=> feat: add features API to rest types

src/hooks/useSetUserProfileEffect.test.ts, src/hooks/useSetUserProfileEffect.ts, src/hooks/useUser.test.tsx, src/hooks/useUser.ts, src/types/rest-types.ts
Adopting `useRestQuery` in `useUser`, and getting some nice type improvements.
=> feat: simplify useUser and extract useUpdateUser

src/hooks/Circles/usePrivatePosts.ts
- Fix query key name in mutation callback so new post is added automatically
=> Fix message cache not updated by new post mutation

package.json, src/test-utils/rest-api-mocking.ts, yarn.lock
Pulling in https://github.com/lifeomic/one-query/pull/38
=> fix: upgrade one-query

package.json, yarn.lock
Pulling in the latest improvements.
=> Upgrade one-query

src/screens/DirectMessagesScreen.tsx
- Display names on messages when it is a group chat
=> Render names on group messages

jest.config.js, jest.setup.ts, src/hooks/useConversations.ts, src/screens/MessageScreen.test.tsx, src/screens/MessageScreen.tsx
- Add button so users can leave a conversation
https://github.com/lifeomic/react-native-sdk/assets/76954025/58c6218d-d6b6-4fee-bc60-dea2588363ef
=> Add delete conversation button

src/components/Messaging/ComposeInputBar.tsx, src/components/Messaging/SearchRecipientsModal.tsx, src/screens/ComposeMessageScreen.tsx, src/screens/DirectMessagesScreen.tsx
- Fixes pill sizes on Android
- Fixes text alignment on message input box 
- Adds Done button on user selection modal
- Exposes styles for the message username signature text
=> fix: Tweak styles for Android, etc

src/screens/DirectMessagesScreen.tsx
=> fix: Expose time style

example/package.json, example/yarn.lock, src/components/Messaging/ComposeInputBar.tsx, src/components/Messaging/SearchRecipientsModal.tsx, src/screens/ComposeMessageScreen.test.tsx, src/screens/ComposeMessageScreen.tsx, src/screens/MessageScreen.tsx, src/test-utils/rest-api-mocking.ts
- Fixes the example app so android can build by updating mmkv to latest
- Adds KeyboardAvoidingViews to the message creation screen so sending can happen with the keyboard open
- Adds a Keyboard dismiss to the background of message creation
- Adds the ability to remove a recipient
- Stretches the Text input so tapping anywhere in the input will focus the text input
- Adds styling to the done button to have the text look correct on the primary background
- Clicking the patient/provider to boxes brings up the modal (not just the plus)
- Fixes a bug where some conversations were not displayed if the current user's profile was not loaded
- Fixes a test setup bug, looks like something changed with one-query
<table>
<tr>
<td><video src="https://github.com/lifeomic/react-native-sdk/assets/2295908 …
=> Conversation UI Fixes

UPGRADING.md
=> docs: add docs for upgrading from 5.x -> 6.x

example/storybook/stories/MyData/LineChart.stories.tsx, src/components/MyData/LineChart/TraceLine.tsx, src/components/MyData/styles.ts, src/components/MyData/useVictoryTheme.ts
- Adds a configuration option on the trace to display a trendline of the trace
=> Add Trendline to My Data Line Chart

src/hooks/useActiveProject.test.tsx
This PR refines the `useActiveProject` test suite to rely _less_ on mocking + asserting `AsyncStorage` function invocations. Instead, it performs logical assertions about the current _state_ of `AsyncStorage` by interacting with the mock instance.
=> chore: improve useActiveProject coverage

package.json, yarn.lock
Just pulling in the latest fixes for `one-query`.
=> fix: update one-query

src/components/HeaderButton.tsx, src/components/TrackTile/ManageTrackers/ManageTrackerRow.tsx, src/hooks/useExchangeToken.test.tsx, src/screens/HomeScreen.tsx, src/screens/ProfileScreen.tsx, src/screens/TrackTileSettingsScreen.tsx
- Cleans up lint issues
- Fixes a bug where the tracker setting screen crashed upon open
=> fix: Fix Lint Warnings and Manage Tracker Error

UPGRADING.md
=> docs: add v8 upgrade docs

src/components/TrackTile/PillarsTile/PillarsTile.tsx, src/components/TrackTile/TrackerDetails/to-procedure-resource.ts, src/components/TrackTile/common/DefaultOnError.test.tsx, src/components/TrackTile/common/DefaultOnError.tsx, src/components/TrackTile/services/TrackTileService.ts, src/screens/TrackTileAdvancedDetailsScreen.tsx, src/screens/TrackTileTrackerScreen.test.tsx, src/screens/TrackTileTrackerScreen.tsx
https://github.com/lifeomic/react-native-sdk/assets/1445395/1877adc2-ef48-4b5b-9f7f-e77a909ead4e
=> Display tracker errors and introduce a >24h error

README.md
=> docs: correct RootProviders examples in README

src/components/Invitations/InviteProvider.tsx, src/types/rest-types.ts
A recent change caused issues when accepting invites. Sometimes, the user will land on the invite required screen. This fixes that.
=> FLME-412: update account list after accepting invite

src/common/DeveloperConfig.ts
=> fix: correct component type for custom consent screen

src/hooks/useConsent.ts
=> docs: add inline comment about activities reset

UPGRADING.md, src/components/Invitations/InviteProvider.tsx
Two:
- Adding upgrade docs for 10.x
- Addressing this follow-up item: https://github.com/lifeomic/react-native-sdk/pull/488#discussion_r1416109064
=> fix: rename store variable and add 9.x -> 10.x upgrading docs

UPGRADING.md, src/hooks/useMe.test.tsx, src/hooks/useMe.ts, src/types/fhir-api-types.ts
#488 opened up the opportunity for a nice consistency in `useMe`.
=> Migrate useMe to be powered by useRestQuery

src/hooks/useActivities.tsx
Adding support for forwarding query options in `useActivities`.
=> fix: support query options for useActivities

src/hooks/useHttpClient.tsx
Improving the local-dev-only error log message for failed HTTP requests.
=> fix: improve dev log message for failed requests

src/types/rest-types.ts
Adding basic, initial support for fetching a file from the Files API. Just typing the basic fields for now.
=> feat: add FHIR files endpoint

src/components/MyData/SleepChart/DailyChart.tsx, src/components/MyData/SleepChart/DataSelector.tsx, src/components/MyData/SleepChart/MultiDayChart.tsx, src/components/MyData/SleepChart/index.test.tsx, src/components/MyData/SleepChart/index.tsx, src/components/ScreenSurface.tsx, src/screens/MyDataScreen.tsx
- Adds data selection tooltips to the sleep data chart
https://github.com/lifeomic/react-native-sdk/assets/2295908/c58fc986-ea3e-47f4-a448-a1fa46e178a0
=> Add Sleep Chart Data Selection

src/types/rest-types.ts
we want to support the current version param when targeting a mobile project
=> feat: support the app version for getting features

src/common/LoggedInProviders.tsx, src/components/ActivityIndicatorView.tsx, src/components/Circles/CreateEditPostModal.tsx, src/hooks/useActiveProject.tsx, src/hooks/useExchangeToken.tsx, src/hooks/useOAuthFlow.tsx, src/hooks/useTabsConfig.tsx
- Cleans up some circular dependency warnings
=> Fix Circular Dependencies

src/common/DeveloperConfig.ts, src/hooks/apps-api.test.tsx, src/hooks/apps-api.tsx, src/types/apps-rest-types.ts
=> feat: add apps api hooks

src/components/Messaging/SearchRecipientsModal.tsx, src/components/TrackTile/TrackerDetails/TrackerDetails.tsx, src/components/TrackTile/TrackerRow/Tracker.tsx, src/screens/ComposeMessageScreen.tsx
- Fix cut off done button on recipients modal due to font scaling
- Adjust size of tracker images to correctly fit
- Adjust size of day picker on tracker
- Fix white border behind recipients modal in dark mode
- Fix white text for tracker text name on home screen due to dark mode
=> Font Scaling/Dark theme fixes

src/common/LoggedInProviders.tsx, src/components/AppConfigSwitcher.tsx, src/components/AppConfigSwitcherButton.tsx, src/hooks/useAppConfig.tsx, src/screens/HomeScreen.tsx
- Include AppConfigSwitcher on HomeScreen (hidden by default)
- Fix button style name
- Clean up log statement
=> Include AppConfigSwitcher on Home

src/screens/DirectMessagesScreen.tsx
- Fixes some display issues with the keyboard showing and hiding
- Hide the keyboard when selecting images to make sure the accessory view isn't cut off
- Moves the accessory view styling to the correctly typed place
<table>
<tr>
<td><b>Before
<td><b>After
<tr>
<td><img width="397" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/0676f090-291d-482d-b611-73714deb6979">
<td><img width="396" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/b5d1ae2a-75c8-4107-9ccd-a71717422519">
<tr>
<td><img width="395" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/ac146608-15a9-4c59-ae6d-eadbad87c242">
<td><img width="397" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/6f327454-9395-4c54-a1e0- …
=> fix; Keyboard interactions with messages
