- example/package.json
- example/yarn.lock
- index.ts
- package.json
- src/hooks/useAPIClients.test.tsx
- src/hooks/useAPIClients.tsx
- yarn.lock
Hopefully obvious I'm not trying to add all the features (auth refresh) or edge cases (401 error handling) here.  For the components that we all agree we don't want to migrate as-is (hopefully not TOO many of these...), I think it makes sense to introduce very small bits like this.  i.e. Auth refresh & 401 error handling can be separate PRs.
I manually tested this out like so, but couldn't find a way to put it into a story yet - that'll also come in subsequent PRs.
```
const { httpClient } = useAPIClients();
useEffect(() => {
httpClient.get('/v1/accounts').then(response => {
console.warn('accounts', response.data);
});
}, []);
```
> (Over) simplified api clients hook, to start

- src/hooks/useAuth.test.tsx
- src/hooks/useAuth.tsx
- src/hooks/useHttpClient.test.tsx
- src/hooks/useHttpClient.tsx
- src/navigators/RootStack.tsx
- Allow for API consumers to report 401s to useAuth
- Have useHttpClient report 401s to useAuth
https://user-images.githubusercontent.com/1445395/221244825-8ec42efe-abc5-487f-86e2-eb70a950d0a3.mov
https://user-images.githubusercontent.com/1445395/221244903-d365095a-569d-4618-afb3-ece98251f373.mov
☝️ waiting for future PR on `Alert` (user error message dialog) usage, error reporting, etc.
> fix: Refresh auth token on 401 http errors

- CONTRIBUTING.md
- package.json
- Document intended dev cycle of a component
- Copy README into dist during build (so it shows up in the [npm listing](https://www.npmjs.com/package/@lifeomic/react-native-sdk))
> Docs and build-README updates

- example/babel.config.js
- example/ios/Podfile.lock
- example/package.json
- example/storybook/stories/NoInternetToastProvider.stories.tsx
- example/storybook/stories/index.ts
- example/yarn.lock
- jest.setup.ts
- package.json
- src/common/RootProviders.tsx
- src/hooks/NoInternetToastProvider.test.tsx
- src/hooks/NoInternetToastProvider.tsx
- src/hooks/index.ts
- yarn.lock
A toast message will be shown when there is no internet on the device and hidden when the connection is restored. A user can swipe the message off screen but it will reappear until internet connection is restored.
- No additional setup required if importing/using RootProviders directly. Otherwise include the NoInternetToast as a sibling alongside the root NavigationContainer. Refer to the setup docs for react-native-toast-message [here](https://github.com/calintamas/react-native-toast-message/blob/main/docs/navigation-usage.md) for more info.
Additional setup and usage docs can be found on in `react-native-toast-message` repo [here](https://github.com/calintamas/react-native-toast-message).
- Jest test coverage
> Add no internet toast message

- example/storybook/stories/BrandConfigProvider/BrandConfigProvider.stories.tsx
- example/storybook/stories/BrandConfigProvider/ExampleBox.tsx
- example/storybook/stories/BrandConfigProvider/ThemeExampleScreen.tsx
- example/storybook/stories/ExampleApp.stories.tsx
- example/storybook/stories/OAuth.stories.tsx
- example/storybook/stories/index.ts
- src/components/BrandConfigProvider/index.ts
- src/components/BrandConfigProvider/theme/Theme.test.tsx
- src/components/BrandConfigProvider/theme/Theme.ts
- src/components/BrandConfigProvider/theme/base/colors.ts
- src/components/BrandConfigProvider/theme/base/index.ts
- src/components/OAuthLoginButton.test.tsx
- src/components/OAuthLoginButton.tsx
- src/hooks/useTheme.test.tsx
- src/screens/LoginScreen.tsx
- Add base wireframe color scheme
- Style the OAuthLoginButton
- Add the DemoApp as a Storybook story
https://user-images.githubusercontent.com/220893/222758453-5a3bcb32-e668-4e64-93c0-cde7795516c4.mov
> PHC-4075 - Add base style [OAuthLoginButton]

- __mocks__/@react-native-async-storage/async-storage.js
- example/babel.config.js
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- jest.setup.ts
- package.json
- src/hooks/useActiveAccount.test.tsx
- src/hooks/useActiveAccount.tsx
- src/hooks/useGetAsyncStorage.ts
- yarn.lock
- Allow passing in accountId to provider to force an account selection. This takes priority over what is in async storage and also still honors the list of accounts returned from `/accounts`, i.e., if the specified account is not present an error is thrown. 
- Reads and writes the selected accountId from async storage so selections persist between sessions
- Add react-query wrapped get async storage hook to simplify usage
> PHC-4151 Cleanup TODOs in useActiveAccount

- src/hooks/useActiveAccount.test.tsx
- src/hooks/useActiveAccount.tsx
- src/hooks/useActiveProject.test.tsx
- src/hooks/useActiveProject.tsx
- src/hooks/useAsyncStorage.ts
- Read/write the selectedProjectId to async storage
- Contains https://github.com/lifeomic/react-native-sdk/pull/65 so review that one first
> PHC-4151 Update useActiveProject to read/write to async storage

- jest.config.js
- package.json
- src/hooks/useActiveAccount.tsx
- src/hooks/useActiveProject.tsx
- src/hooks/useAuth.tsx
- src/hooks/useHttpClient.tsx
- src/hooks/useOAuthFlow.tsx
- Move TypeScript compilation step out of Jest so that tests can be run with `yarn jest` and not get TypeScript errors
- Update `yarn test` to do a full build with `tsc --noEmit`
- Add `process.env.NODE_ENV !== 'test'` conditional around `console.warn` statements to clean up test output
(Note, I tried adding `tsc --noEmit` to CI, but that ran into a bunch of errors because `example/**/*` isn't being built yet.)
> PHC-4075 - Improve test development

- example/storybook/stories/TrackTile/TrackerDetails.stories.tsx
- src/components/TrackTile/ManageTrackers/ManageTrackerRow.tsx
- src/components/TrackTile/ManageTrackers/ManageTrackers.tsx
- src/components/TrackTile/OpenSettingsButton.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/QuickAddItem.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/AdvancedTrackerEditor.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/CodingSubCategoryRow.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerEditor/ValueEditor/ValueDisplay.tsx
- src/components/TrackTile/TrackerDetails/DatePicker.tsx
- src/components/TrackTile/TrackerDetails/TrackAmountControl.tsx
- src/components/TrackTile/TrackerDetails/TrackerDetails.tsx
- src/components/TrackTile/TrackerDetails/TrackerHistoryChart/Chart.tsx
- src/components/TrackTile/TrackerDetails/TrackerHistoryChart/Paginator.tsx
- src/components/TrackTile/TrackerDetails/UnitPicker.tsx
- src/components/TrackTile/TrackerDetails/unit-display.ts
- src/components/TrackTile/TrackerRow/Tracker.tsx
- src/components/TrackTile/formatters/dateFormatter/index.ts
- src/components/TrackTile/formatters/formatters.test.ts
- src/components/TrackTile/formatters/numberFormatter/index.ts
- src/components/TrackTile/util/convert-value.test.ts
- src/components/TrackTile/util/convert-value.ts
- src/screens/TrackTileTrackerScreen.tsx
- tsconfig.json
- Make it so we no longer need to add an alias to the metro configuration
> fix: Use relative paths for i18n imports

- example/storybook/stories/CustomAppTileScreen.stories.tsx
- src/components/tiles/TilesList.tsx
- src/navigators/HomeStack.tsx
- src/navigators/SettingsStack.tsx
- src/screens/AppTileScreen.tsx
- src/screens/CustomAppTileScreen.tsx
- src/screens/HomeScreen.test.tsx
- src/screens/SettingsScreen.test.tsx
- src/screens/SettingsScreen.tsx
- src/screens/TrackTileSettingsScreen.tsx
- src/screens/TrackTileTrackerScreen.tsx
This addresses some feedback and fixes an incorrect import resulting (I think) from a merge error
- Fix import
- Update route names to reflect their stack location
> chore: Standardize route names based on stack

- src/components/TrackTile/TrackTile.tsx
- src/components/TrackTile/TrackerRow/Tracker.tsx
- src/components/TrackTile/TrackerRow/TrackerRow.tsx
- src/screens/HomeScreen.tsx
- Adjusted TrackTile spacing to tighten it up to match PillarsTile
- Removed SafeAreaView as it is causing issues and we already have safe area protection in react-navigation header and tab navigation
https://user-images.githubusercontent.com/220893/233506469-6a55130d-bb88-4656-bd57-5c3b1dc33b37.mov
https://user-images.githubusercontent.com/220893/233506493-727dd0ae-5aef-46b0-8b6c-36efb9f73593.mov
> PHC-5429 - feat: Final TrackTile in TileList tweaks

- src/components/TrackTile/TrackerRow/TrackerRow.tsx
- Fixes the double conversion issue. `Tracker` assumes values are the raw value. For Procedures, it assumes values are in seconds and then converts it to the display value. The `TrackerRow` was pre-converting the which resulted in double conversions.
- Also fixes the name of the style to match the component
https://user-images.githubusercontent.com/2295908/234898043-d1ff30b7-e94c-4bc8-935e-51d0ee4a25ba.mov
> fix: PHC-4697 Remove double convert logic for Procedure trackers

- src/components/ActivityIndicatorView.tsx
- src/components/AppNavHeader.tsx
- src/components/ScreenSurface.tsx
- src/components/TrackTile/PillarsTile/Pillar.tsx
- src/components/TrackTile/PillarsTile/PillarsTile.tsx
- src/components/TrackTile/TrackTile.test.tsx
- src/components/TrackTile/TrackTile.tsx
- src/components/TrackTile/TrackerRow/RadialProgress.tsx
- src/components/TrackTile/TrackerRow/Tracker.tsx
- src/components/TrackTile/TrackerRow/TrackerRow.tsx
- src/components/tiles/Tile.tsx
- src/components/tiles/TilesList.tsx
- src/navigators/TabNavigator.tsx
- src/screens/HomeScreen.tsx
- Add elevated light style to the header and tab navigation
- Smaller and more relaxed title typography
- Fixed issue with nested ScrollView in both TileList and HomeScreen.  Replaced with new ScreenSurface.
- New ScreenSurface component.   This is meant to be the base of any scrolling screen like notifications or settings, but just focused on the home screen in this PR
- Tweaked Pillar and TrackTile styles to be more like PMA
- Updated to our createStyles/useStyles system in a couple components where it made sense as I was adjusting default styles
https://user-images.githubusercontent.com/220893/235037731-03dc8419-3ecd-4845-b9a0-70a9c32d3db0.mov
https://user-images.githubusercontent.com/220893/235037776-98c5d8e6-a8d1-409e-b75d-579542b7a3df.mov
> PHC-4621 - Update style and surfaces toward new design

- src/hooks/useEnvironmentSelection.tsx
In the event you load straight into the app and never render the EnvironmentSelection toggle, the useEnvironmentSelection hook would default to using the primary environment. This fixes the hook to sync with the value in async storage.
> chore: Load initial state from async storage

- src/components/TrackTile/PillarsTile/Pillar.tsx
- src/components/TrackTile/PillarsTile/PillarsTile.tsx
- src/components/TrackTile/icons/indicator/index.tsx
- Make pillars tile slightly taller
- Update margins on either side of pillars and between icons/text
- Update pillar background color
- Tighten up pillars
- Make icons smaller
- Make text under pillars smaller
- Use createStyles 
| Before | After |
| - | - | 
| ![image](https://user-images.githubusercontent.com/220893/235991866-a5bed589-5597-4c0a-99c3-8743d468b182.png) | ![image](https://user-images.githubusercontent.com/220893/235991365-1492e199-387a-4a78-8b46-689ebcf3b020.png) |
> PHC-4621 - Update pillar styles

- example/ios/example.xcodeproj/project.pbxproj
- jest.setup.ts
- src/common/DeveloperConfig.test.tsx
- src/common/DeveloperConfig.ts
- src/screens/CustomAppTileScreen.tsx
This makes it so that, if you configure an app tile with a bundle id like `com.lifeomic.components-app://device-config` (in this app's example), and that URL is NOT configured in `developerConfig`, then it'll show an error screen (below) instead of attempting to load the URL in a browser.
> Allow and detect custom app tiles with bundleId

- bin/scripts/buildDeclaredStyles.js
- package.json
- Adds a script that:
- Updates all `declare module '@styles'` to be `declare module '<relative path to BrandConfigProvider/styles/types>'`
- Adds an import to the `dist/index.d.ts` file to include the declared styles
<table>
<tr>
<td><b>Before
<td><b>After
<tr>
<td><img src="https://github.com/lifeomic/react-native-sdk/assets/2295908/a1ef238b-3819-4739-9e7d-b9cc5034c0ab" />
<td><img src="https://github.com/lifeomic/react-native-sdk/assets/2295908/15b43b9b-7029-4761-9a39-cc261becad7d" />
</table>
> fix: Add Script to Fix Declared Styles for Deployment

- src/screens/LoginScreen.tsx
- Show dialog when auth fails instead of silently navigating back to the login screen
- Only reveal error text in __DEV__ mode otherwise show generic message
> chore: Handle auth error

- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.test.tsx
- src/components/TrackTile/TrackerDetails/NumberPicker.tsx
- src/components/TrackTile/TrackerDetails/TrackAmountControl.tsx
- src/components/TrackTile/TrackerDetails/TrackerDetails.test.tsx
- src/components/TrackTile/TrackerDetails/TrackerDetails.tsx
- src/components/TrackTile/TrackerDetails/unit-display.ts
- src/components/TrackTile/services/TrackTileService.ts
- src/screens/TrackTileTrackerScreen.tsx
- Tracker details design updates
- We used to allow for free entry of the target but now we a defined list to selected from
- Possible values depend on the defined stepAmount for the unit with an upper limit of stepAmount x 50.
- Looks like I recently introduced some undesired behavior with the counter incrementing/decrementing that will be address in a follow up
https://github.com/lifeomic/react-native-sdk/assets/76954025/d8e16b80-db1c-4b43-9b48-806ea5de862a
> PHC-4837 Redesign tracker details

- example/storybook/stories/TrackTile/AdvancedTrackerDetails.stories.tsx
- example/storybook/stories/TrackTile/TrackerDetails.stories.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.test.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.tsx
- src/components/TrackTile/TrackerDetails/TrackerDetails.test.tsx
- src/components/TrackTile/TrackerDetails/TrackerDetails.tsx
- src/components/TrackTile/TrackerDetails/TrackerHistoryChart/TrackerHistoryChart.tsx
- src/navigators/types.tsx
- src/screens/TrackTileAdvancedDetailsScreen.tsx
- src/screens/TrackTileTrackerScreen.tsx
* Adds optional prop to `TrackerDetails` and `AdvancedTrackerDetails` to receive a date
* If the `referenceDate` is provided, the component uses that date instead of the current date
* Prevents passing a `referenceDate` in the future
* Adds `knobs` to storybook
https://github.com/lifeomic/react-native-sdk/assets/600650/091bf3f5-b3c3-484c-88f9-d4078da55628
> [PE-124] Update TrackerDetails to accept reference date

- src/hooks/useHandleAppTileEvents.test.ts
- src/hooks/useHandleAppTileEvents.ts
* Adds a handler for deep linking into `TrackTileDetails` screen
* Adds the `useTrackers` hook to the `useHandleAppTileEvents` hook to have tracker details available
> feat: handle deep link to TrackTile

- example/AppDemo.tsx
- example/storybook/helpers/CenterView.tsx
- example/storybook/helpers/SafeView.tsx
- example/storybook/index.tsx
- example/storybook/stories/BrandConfigProvider/BrandConfigProvider.stories.tsx
- example/storybook/stories/ExampleApp/ExampleApp.stories.tsx
- example/storybook/stories/NoInternetToastProvider.stories.tsx
- example/storybook/stories/TrackTile/AdvancedTrackerDetails.stories.tsx
- example/storybook/stories/TrackTile/Indicator.stories.tsx
- example/storybook/stories/TrackTile/ManageTrackers.stories.tsx
- example/storybook/stories/TrackTile/Pillar.stories.tsx
- example/storybook/stories/TrackTile/PillarsTile.stories.tsx
- example/storybook/stories/TrackTile/TrackTiles.stories.tsx
- example/storybook/stories/TrackTile/Tracker.stories.tsx
- example/storybook/stories/TrackTile/TrackerDetails.stories.tsx
- example/storybook/stories/TrackTile/TrackerHistoryChart.stories.tsx
- example/storybook/stories/Wearables/SelectorRow.stories.tsx
- example/storybook/stories/Wearables/SelectorView.stories.tsx
- example/storybook/stories/Wearables/SwitchRow.stories.tsx
- example/storybook/stories/Wearables/SyncTypeSelectionRow.stories.tsx
- example/storybook/stories/Wearables/SyncTypeSelectionView.stories.tsx
- example/storybook/stories/Wearables/WearablesView.stories.tsx
- src/common/DeveloperConfig.ts
- src/components/AppNavHeader.tsx
- Turned on-simulator storybook UI off to prevent safe-area-view from automatically being added
- Fixed all stories related to this change
- Added a developerConfig prop to control `statusBarHeight` of the AppNavHeader
- Moved example of additional tab navigator tab to the stories
> feat: Update safe area view

- src/hooks/useWearables.ts
- Updates setting sync types to use PUT: [lifeomic/ehr-service/.../wearables.ts#L80](https://github.com/lifeomic/ehr-service/blob/master/src/api/controllers/wearables.ts#L80)
> fix: Wearable Sync Type Updates Should use PUT

- example/storybook/helpers/oauthConfig.ts
- example/storybook/stories/ActivityIndicatorView.stories.tsx
- example/storybook/stories/ExampleApp/ExampleApp.stories.tsx
- example/storybook/stories/OAuth.stories.tsx
- src/components/AppNavHeader.tsx
- src/components/LogoHeader.tsx
- Correct header margins for Android
- Prevent OAuth.stories from loading more than once
| Before | After |
|-|-|
|![Screenshot 2023-06-05 at 5 38 35 PM](https://github.com/lifeomic/react-native-sdk/assets/220893/011a3db8-0dfe-49ba-8861-bfb21d04ba6c)|![Screenshot 2023-06-05 at 5 39 29 PM](https://github.com/lifeomic/react-native-sdk/assets/220893/57b66c71-5507-4726-b9a1-d0abf9111209)|
> fix: Correct header margins for Android

- src/components/TrackTile/TrackerDetails/coerce-to-nonnegative-value.ts
- src/components/TrackTile/hooks/useTrackers.ts
- Fixes consistency issue for the pillar trackers where a changed value (like target) will not persist through screen navigation.
- Fixes rounding issue when selecting a fractional value via the target selector
> fix: Set pillarTrackers state during onChange

- .eslintrc.js
- src/hooks/useConsent.test.tsx
- src/hooks/useConsent.ts
- src/navigators/RootStack.tsx
- src/screens/ConsentScreen.test.tsx
- src/screens/ConsentScreen.tsx
1. Avoid rendering home screen before consent by being eager with useConsent's `isLoading`
2. Resolve a duplicate-consent-created issue, and also simplify logic, by relying on assigned consents (instead of default-form) and using PATCH instead of POST
> fix: Resolve some consent bugs

- src/hooks/useFhirClient.test.tsx
- src/hooks/useFhirClient.tsx
`patient-service` expects `pageSize` to be a string.
> fix: convert pageSize to string in useSearchResourcesQuery

- README.md
- __mocks__/ImageMock.tsx
- __mocks__/svgMock.tsx
- example/storybook/index.tsx
- example/storybook/stories/CustomScreenInjection/CustomScreenInjection.stories.tsx
- example/storybook/stories/CustomScreenInjection/customScreens/NavigationPlaygroundScreen.tsx
- example/storybook/stories/CustomScreenInjection/customScreens/UserDetailsScreen.tsx
- example/storybook/stories/CustomScreenInjection/customScreens/UsersScreen.tsx
- example/storybook/stories/CustomScreenInjection/customScreens/index.tsx
- example/storybook/stories/CustomScreenInjection/customScreens/types.ts
- example/storybook/stories/index.ts
- jest.config.js
- src/common/DeveloperConfig.ts
- src/components/DeveloperConfigProvider.test.tsx
- src/navigators/HomeStack.tsx
- src/navigators/index.ts
- This PR exposes the Home navigation stack so custom screens can be added to it.
- In this video, The FHIR Example screen is a custom screen that was added to the Home navigation stack.
- The `App Tile` screen is an existing screen, and demonstrates that we can from custom screens to "LifeOmic" screens.
https://github.com/lifeomic/react-native-sdk/assets/19395435/ccea8236-41fd-4175-9fa1-8a98459dacff
> feat: Inject custom screens in the Home navigation stack

- src/components/BrandConfigProvider/styles/createStyles.ts
- src/components/MyData/LineChart/DataSelector.tsx
- src/components/MyData/LineChart/Title.tsx
- src/components/MyData/LineChart/TraceLine.tsx
- src/components/MyData/LineChart/index.test.tsx
- src/components/MyData/LineChart/index.tsx
- src/components/MyData/LineChart/useChartData.test.ts
- src/components/MyData/LineChart/useChartData.ts
- src/components/MyData/styles.ts
- src/components/MyData/useVictoryTheme.ts
- Adds the ability to specify chart styles using style overrides
- Makes the independent axis labels use the trace color
- Adds the ability to set a color on the trace
> fix: PHC-4968 Add Chart Style Overrides

- src/components/MyData/LineChart/DataSelector.tsx
- Fixes an issue where the label was displayed below the highest point if the lower points scale was narrow
- Fixes an issue where 3+ digit numbers were too large for the bubble. We will likly need to address this again at some point for 4+ character strings.
> fix: PHC-4968 Fix Chart Label Render Issues

- example/storybook/stories/MyData/MyData.stories.tsx
- src/components/BrandConfigProvider/icons/IconProvider.tsx
- src/components/MyData/LineChart/TraceLine.tsx
- src/components/MyData/LineChart/index.test.tsx
- src/components/tiles/TilesList.tsx
- src/hooks/useAppConfig.ts
- src/navigators/HomeStack.tsx
- src/navigators/types.tsx
- Adds a tile for the native My Data Screens
- Fixes a bug where the chart axis wasn't displayed if there was no data on the chart
https://github.com/lifeomic/react-native-sdk/assets/2295908/89c84d06-73ff-4b8e-8eb9-35ca9f36d751
> fix: PHC-4969 Add My Data Screen to Tiles List

- src/components/MyData/LineChart/TraceLine.tsx
- Fixes an issues where tick labels were rendered off the chart when trace doesn't have data
<table>
<tr>
<td><b>Before
<td><b>After
<tr>
<td><img width="372" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/6754cc82-f483-4cde-ab0a-236f6e1aa0b1">
<td><img width="389" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/99fecb65-7c0e-4e46-8fe4-31c2b761c2e4">
</table>
> PHC-4968 Fix Empty Tick Labels

- src/hooks/useSubjectProjects.test.tsx
- src/hooks/useSubjectProjects.tsx
Instead of performing a GET on an invalid URL return an empty array when subjects is not populated
> fix: Improve handling when no subjects exist

- src/components/Wearables/SyncTypeSelectionView.tsx
- src/components/Wearables/WearableRow.tsx
This hides background sync if it can't be enabled, and also provides a translation value for BMI.
https://github.com/lifeomic/react-native-sdk/assets/1445395/3674f13d-0464-4886-8a09-ddadce4b1d68
> Hide background sync toggle if onToggleBackgroundSync is not provided

- src/components/TrackTile/hooks/test/useAxiosTrackTileService.test.ts
- src/components/TrackTile/hooks/useAxiosTrackTileService.ts
- src/hooks/useActiveAccount.test.tsx
- src/hooks/useActiveAccount.tsx
- src/hooks/useActiveProject.test.tsx
- src/hooks/useActiveProject.tsx
- src/hooks/useOAuthFlow.test.tsx
- src/hooks/useOAuthFlow.tsx
- src/screens/ProfileScreen.tsx
To support logout and user switching:
- Clear selected account when the user id changes
- Clear selected project when the user id changes
- Clear cached trackers when the user id changes
- Clear queryClient cache on logout
Also added a _DEV_ only field to the profile screen to show the current project name.
N/A
> fix: Clear caches on logout

- example/storybook/stories/SharingRenderers/PointBreakdown.stories.tsx
- example/storybook/stories/SharingRenderers/index.ts
- example/storybook/stories/index.ts
- src/components/SocialShare/renderers/point-breakdown.test.tsx
- src/components/SocialShare/renderers/point-breakdown.tsx
- fixes a bug where the trace color was not used in the point breakdown export
- Added some stories for using the sharingRenderer
https://github.com/lifeomic/react-native-sdk/assets/2295908/c9fbbba5-d390-42eb-af4d-cae053d0edb4
> fix: PHC-4836 Fix Point Breakdown Colors and Add Story

- README.md
- example/android/app/src/main/java/com/example/MainApplication.java
- example/android/app/src/main/java/com/example/RNTLaunchScreen.java
- example/android/app/src/main/res/layout/splash_screen.xml
- example/ios/example.xcodeproj/project.pbxproj
- example/ios/example/RNTLaunchScreen.m
- src/components/LaunchScreen.ts
- src/screens/LoginScreen.tsx
- Adds the ability to provide a native view, registered as `RNTLaunchScreen`, that will be displayed behind the long button if present. 
- Adds documentation to the README specifying how to configure this view
> PHC-5065 Display Splash Screen Behind Login Screen

- src/components/Circles/CreateEditPostModal.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.tsx
- src/components/TrackTile/TrackerDetails/TrackerDetails.tsx
- src/navigators/RootStack.tsx
- Fixes the Keyboard Avoiding view to not cut off the `Post` button when the text is taller than a few lines
- Uses `ScrollView` from react native (could cause the app to crash)
- Requires an invite messaging was showing up briefly while loading the project. Fixes the logic to only show it once projects and accounts are loaded
I think the missing X button is an issue with my set up and can be ignored. I am seeing it show up in other apps using the SDK
> fix: Visual Bug Fixes

- src/hooks/useWearableBackfill.test.tsx
- src/hooks/useWearableBackfill.tsx
- The graphql server did not like the old format of querying patient multiple times in the same query. This reworks the query and logic to query for multiple observations/procedures and alias them with the format `[type]_(Observations|Procedures)`
> fix: Backfill Status Query

- src/screens/NotificationsScreen.tsx
- NotificationScreen now uses a ScrollView to handle notification overflow
- Assigns defaultStyles to every component to allow for tweaking these styles in consuming apps
> Assign defaultStyles for notification screen components

- src/components/AppNavHeader.tsx
- src/hooks/useHandleAppTileEvents.test.ts
- src/hooks/useHandleAppTileEvents.ts
- src/navigators/types.tsx
- src/screens/AuthedAppTileScreen.tsx
- Adds logic to handle the back arrow or hardware back button
<table>
<tr>
<td><video src="https://github.com/lifeomic/react-native-sdk/assets/2295908/498fa7e1-4872-4528-b3c1-cfdac238104b" />
<td><video src="https://github.com/lifeomic/react-native-sdk/assets/2295908/05a508a4-61c6-45ab-aea2-7023ad0f3c7b" />
</table>
> fix: App Tiles can Register a Go Back Handler Now

- src/hooks/useActiveAccount.tsx
- src/navigators/RootStack.tsx
- Restores the Root Loading logic
- Fixes an issue where `useActiveAccount` could be in a state where `isFetched: true` and `isLoading: false` but not actually have set the active account data if possible
> fix: Account Loading Logic Waits for Selection

- src/components/MyData/LineChart/DataSelector.tsx
- fixes an issue where the tooltip was not displayed if their was no `point1` selected. Switches to calculating x based off of the selected date
> fix: PHC-4968 Fix Data Selection for Missing Point1

- src/hooks/useActiveAccount.test.tsx
- src/hooks/useActiveAccount.tsx
- src/hooks/useActiveProject.test.tsx
- src/hooks/useActiveProject.tsx
- src/hooks/useSubjectProjects.test.tsx
- src/hooks/useSubjectProjects.tsx
- Reverts the `isSettled` changes that did not work
- Switches from state/effect logic to `useMemo` for account and project selection. The old way allowed for some extra renders where `isLoading: false` and `isFetched: true` but the correct account/project had not actually been selected which caused the `need an invitation` warning to be displayed
> Use Memo for Account/Project Selection

- src/hooks/useHandleAppTileEvents.test.ts
- src/hooks/useHandleAppTileEvents.ts
When opening a lifeology course via the today tile on Android, the web view sends a message with `data = undefined`. Our message parser tries to parse undefined, and causes the app to crash.
This message is not sent in iOS.
> fix: Handle errors during parsing the WebView messages

- lib/i18n/locales/en.json
- src/common/RootProviders.tsx
- src/components/HeaderButton.tsx
- src/hooks/index.ts
- src/hooks/useAppConfig.ts
- src/hooks/useOnboardingCourse.test.tsx
- src/hooks/useOnboardingCourse.tsx
- src/navigators/RootStack.tsx
- src/navigators/types.tsx
- src/screens/ConsentScreen.test.tsx
- src/screens/ConsentScreen.tsx
- src/screens/OnboardingCourseScreen.test.tsx
- src/screens/OnboardingCourseScreen.tsx
- src/screens/TrackTileAdvancedEditorScreen.tsx
This PR adds an onboarding course screen. This screen is rendered either after accepting the consent if it exists, or after accepting the invitation. When a course is launched, a key is saved in `AsyncStorage` so we don't launch it a second time.
https://github.com/lifeomic/react-native-sdk/assets/19395435/1dca127b-5b41-485b-8077-41456dbb8bfa
> feat: Onboarding course

- src/common/DeveloperConfig.ts
While changing the theme, I noticed `accentColor` is not actually used. Will also update `react-native-starter` next.
N/A
> chore: remove outdated accent color comment

- src/components/MyData/LineChart/useChartData.test.ts
- src/components/MyData/LineChart/useChartData.ts
- Default query uses 10 as the page size. This changes the query to query for more data based on days in the interval and the number of codes.
> fix: Fix My Data Query for Large Date Ranges

- example/storybook/stories/ExampleApp/ExampleApp.stories.tsx
- src/components/LogoHeader.tsx
- Adds ability to pass an Element to the LogoHeader, e.g., Buttons
- Adds optional parameters to absolutely position image and the item along the horizontal axis
- Preserves default positioning by aligning items center if alignment props are not specified.
- Adds new visible prop
- Adds new hook useEmitLogoHeaderOptions to customize logo settings per screen
- Restores defaults (passed as props to LogoHeader) when leaving the screen
- Merges updated options with defaults so options such as ImageSource only have to specified once
- The useEmitLogoHeaderOptions must be placed within the screen which will prevent using the default screens with this effect. It would be a better experience if this was injectable (perhaps via the DeveloperConfig). …
> feat: Update LogoHeader to be customizable per screen

- example/storybook/stories/ExampleApp/ExampleApp.stories.tsx
- src/common/DeveloperConfig.ts
- src/common/ThemedNavigationContainer.tsx
- src/components/Circles/__tests__/Post.test.tsx
- src/components/Circles/__tests__/PostList.test.tsx
- src/components/Circles/__tests__/ReactionsToolbar.test.tsx
- src/components/Circles/__tests__/Thread.test.tsx
- src/components/Circles/__tests__/ThreadComment.test.tsx
- src/components/LogoHeader.tsx
- src/components/MyData/LineChart/index.test.tsx
- src/components/tiles/TilesList.test.tsx
- src/hooks/useLogoHeaderOptions.tsx
- src/hooks/useWearableBackfill.test.tsx
- src/navigators/HomeStack.tsx
- src/navigators/NotificationsStack.tsx
- src/navigators/SettingsStack.tsx
- src/navigators/types.tsx
- src/screens/AccountSelectionScreen.test.tsx
- src/screens/ConsentScreen.test.tsx
- src/screens/HomeScreen.test.tsx
- src/screens/InviteRequiredScreen.test.tsx
- src/screens/MyDataScreen.test.tsx
- src/screens/NotificationsScreen.test.tsx
- Adds stack navigation listeners to sync LogoHeader with options specified in DeveloperConfig
https://github.com/lifeomic/react-native-sdk/assets/76954025/f006f11d-d934-4ac1-9319-bb9b0d7046e1
https://github.com/lifeomic/react-native-sdk/assets/76954025/364cad91-6697-4819-a57c-6a5c6f1fca28
> feat: Configure LogoHeader per-screen at DeveloperConfig

- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.test.tsx
- src/components/TrackTile/TrackerDetails/AdvancedTrackerDetails/AdvancedTrackerDetails.tsx
- src/components/TrackTile/hooks/test/useTrackerValues.test.ts
Can anyone think of a reason not to default these to the same styling?  I think they just accidentally evolved/diverged over time.
Before:
After:
> Fix: Make AdvancedTrackerDetails history chart default to same style as TrackerDetails

- src/hooks/useActiveProject.tsx
- src/hooks/useMe.ts
- src/hooks/useSetUserProfileEffect.test.ts
- src/hooks/useSetUserProfileEffect.ts
- src/hooks/useUser.test.tsx
- src/hooks/useUser.ts
- src/navigators/RootStack.tsx
- src/screens/ProfileScreen.test.tsx
- src/types.ts
- src/types/rest-types.ts
- Adds a call for updating a user's profile info
- Adds an effect hook to set the user's last/first name based on the patient if it has a name already
> fix: Set User's Real Name on Launch if Missing

- src/hooks/useUnreadMessages.test.tsx
- src/hooks/useUnreadMessages.tsx
I created a secondary local hook that just deals with `useAsyncStorage` to simplify the logic.  This will allow `useUnreadMessages` to grow with whatever else we will need for new message notification.
Since our AsyncStorage wrapper uses React Query for memory caching, I also removed the `useState` hook which is what was causing it to change on every render.
> Fix state change on every render

- src/components/MessagesTile/MessagesTile.tsx
- src/hooks/useNotificationManager.tsx
- src/hooks/useUnreadMessages.test.tsx
- src/hooks/useUnreadMessages.tsx
- src/screens/DirectMessagesScreen.tsx
- src/screens/MessageScreen.tsx
- useUnreadMessages now tracks read receipts when the user opens the DM screen; the read receipt is used to compare notification timestamps to determine new unread messages
- NotificationManager is can now strictly be used for the NotificationTab badges/tracking new notifications
- Fixed the order of unread messages on the message screen so the newest unread message will always appear at the top
> chore: useUnreadMessages tracks read receipts

- src/components/MessagesTile/MessagesTile.test.tsx
- src/components/MessagesTile/MessagesTile.tsx
- src/hooks/Circles/usePrivatePosts.ts
- src/hooks/useMyMessages.tsx
- src/hooks/useUnreadMessages.test.tsx
- src/hooks/useUnreadMessages.tsx
- src/navigators/types.tsx
- src/screens/MessageScreen.test.tsx
- src/screens/MessageScreen.tsx
This PR is mostly a refactor with very little functional change. The MessageScreen has been simplified by extracting all the unread message/user list logic to a new hook, useMyMessages. 
There is one change to the UX on the MessageScreen, instead of relying on scrolling beyond the content height the user must tap the "Load More" button. This will accommodate changes in screen size. See video below.
https://github.com/lifeomic/react-native-sdk/assets/76954025/71fc005f-d42d-4d7c-8118-eca938ccb74a
> chore: Extract MessageScreen logic to hook

- src/screens/MessageScreen.tsx
- Fixes the vertical alignment of the notification badge to be centrally aligned
Before
After
> fix: Align Message Notification Badge Vertically

- example/storybook/stories/BrandConfigProvider/BrandConfigProvider.stories.tsx
- src/common/AppConfigNotifier.tsx
- src/components/BrandConfigProvider/BrandConfigProvider.tsx
- src/components/BrandConfigProvider/icons/IconProvider.tsx
- src/hooks/useAppConfig.tsx
- Adds the ability to inject the brand, defined within the App Config, once it is loaded.
- Some amount of compile time config will still be needed for unauthenticated screens but this allows us to update styles post an app store release
- Adds the ability to provide icon aliases to change icons at runtime. This is particularly useful for app tiles and circle tiles that allow icon injection based on their `id` if a customer wants to change to a new or different app tile, they can update the iconAliases to include the correct mapping for the new icon outside of an app store release. This would also allow a customer to load all their custom icons (similar to Chromicons) and then pick and choose them from the API at a later date.
> feat: Inject Brand from App Config

- src/hooks/useAppConfig.tsx
This fixes https://github.com/lifeomic/react-native-sdk/pull/381#discussion_r1337183582 so that the compiler will catch the bug even without a testcase
> Fix typing on app tile settings

- README.md
- src/common/DeveloperConfig.ts
- src/components/DeveloperConfigProvider.test.tsx
- src/navigators/HomeStack.tsx
This PR adds support for setting a custom home screen.
> feat: Set a custom home screen

- src/components/Invitations/InviteProvider.test.tsx
- src/components/Invitations/InviteProvider.tsx
- src/hooks/useActiveAccount.test.tsx
- src/hooks/useActiveAccount.tsx
- Clear the pending invite status as soon as we've accepted the invite to prevent repeated attempts at accepting the invite. I've seen this manifest when setActiveAccountId fails to set the new account.
- Remove the check that only allows accounts returned from the API to be set from setActiveAccountId. We are hitting a race condition here and this check is resulting in quite a bit of pain. The risk of allowing the setting of an invalid account is low to begin with and any inappropriate account headers sent will be rejected by the API.
> Fix couple invite flow quirks

- src/components/TodayBadge.tsx
- src/components/tiles/TilesList.tsx
- src/hooks/todayTile/useTodayTasks.test.tsx
- src/hooks/todayTile/useTodayTasks.tsx
- src/navigators/HomeStack.tsx
- src/navigators/types.tsx
- Switches the refetch tasks logic to use the route listeners based on a route param, removes useFocusEffect which caused  duplicate queries on load
- Adds a specialized hook for invalidating the today tasks cache
- Adds a delay so today activity interactions can settle on the backend before fetching the latest count (3.5 seconds worked well during my testing)
> Add an Invalidate Today Tasks Hook

- src/hooks/useHandleAppTileEvents.test.ts
- src/hooks/useHandleAppTileEvents.ts
- Before, all stack actions were blocked if the app tile had navigated
- After, only go back actions will be prevented if the app tile has navigated
<table>
<tr>
<td><video src="https://github.com/lifeomic/react-native-sdk/assets/2295908/82a3abbe-92b8-428f-a3ed-bc080898ce87" />
<td><video src="https://github.com/lifeomic/react-native-sdk/assets/2295908/897ae543-cb9f-4e29-81d8-6802d03842fc" />
</table>
> Only Block Go Back for App Tiles

- src/hooks/Circles/usePrivatePosts.ts
- src/hooks/useMyMessages.tsx
- src/navigators/HomeStack.tsx
- src/screens/MessageScreen.test.tsx
- src/screens/MessageScreen.tsx
Load the latest message between two users on the My Messages screen.
> Add message preview

- src/screens/LoginScreen.test.tsx
- After https://github.com/lifeomic/react-native-sdk/pull/404 we were running into https://github.com/jestjs/jest/issues/6434#issuecomment-525576660. The comment indicated adding `jest.useFakeTimers()` to a beforeEach for all tests.
> Fix Login Screen Tests

- src/screens/AuthedAppTileScreen.tsx
Supply an `incognito={true}` prop the webview for app tiles. This will prevent them from excessively caching.
> fix: use incognito prop for webview

- src/common/RootProviders.tsx
- src/navigators/RootStack.tsx
Injecting custom providers used to be as simple as putting them underneath RootProviders but many hooks are no longer available in RootProviders. This was caused by a refactor to separate hooks and screens that require authentication from unauthenticated hooks and screens. Splitting them out solved a number of issues including premature API requests but resulted in loosing access to the authenticated hooks within injected custom providers.
The issues that the original refactor hoped to solve for were achieved by splitting out the LoggedInStack from the RootStack and moving the providers to the LoggedInStack and out of the RootProviders was most likely unnecessary. 
Although the providers contained within LoggedInProviders could have been moved directly back into RootProviders I've opted …
> Move LoggedInProviders back to RootProviders

- src/types/fhir-api-types.ts
- src/types/rest-types.ts
This PR adds support for interacting with the FHIR API fully type-safe via the existing `one-query` hooks. It puts in place a small system that allows for easily adding new resource types.
This video showcases the developer experience.
https://github.com/lifeomic/react-native-sdk/assets/14932834/8e945529-7f1f-42cf-9914-c309446650b3
> FLME-278: add basic FHIR types to the useRest hooks

- src/hooks/useExchangeToken.test.tsx
- src/hooks/useExchangeToken.tsx
- src/types/rest-types.ts
This API was simplified to _not_ require passing the `accessToken` in the request body. It's now gather from the (also required) `Authorization` header.
> fix: simplify useExchangeToken hook

- example/storybook/helpers/DataProviderDecorator.tsx
- example/storybook/stories/ExampleApp/ExampleApp.stories.tsx
- example/storybook/stories/SettingsScreen/SettingsScreen.stories.tsx
- src/common/LoggedInProviders.tsx
- src/hooks/useAppConfig.test.tsx
- src/hooks/useAppConfig.tsx
- src/screens/AppTileScreen.test.tsx
The `useAppConfig` hook currently uses a provider + custom logic for fetching -- we can achieve the same result with less code by just using `useRestQuery`.
I had to make a few other changes in response to the refactor. I explain them each below.
> feat: simplify useAppConfig by using one-query hook

- src/hooks/useActiveAccount.test.tsx
- src/hooks/useActiveAccount.tsx
This PR simplifies a number of pieces of logic in `useActiveAccount` that seemed to be no longer useful.
I've highlighted each change below via a comment -- review appreciated.
> Remove redundant/unused logic in useActiveAccount

- src/types/fhir-api-types.ts
This will help us avoid having to use `.id!` everywhere. Mark the `id` property as defined on FHIR responses!
> fix: mark id as defined in FHIR operations

- src/hooks/useAsyncStorage.tsx
Proposing deprecating `useAsyncStorage` in favor of `useStoredValue`, introduced in #437.
I was going to try to migrate more use cases of `useAsyncStorage` to `useStoredValue`, but it's not so simple. Some of the features powered by `useAsyncStorage` are in end-user hands, and their stored values cannot be lost (e.g. onboarding course completed, notification read time).
So for now, would just like to encourage no _additional_ usages of `useAsyncStorage`. We can worry about migrating call sites of useAsyncStorage later.
- Your changes...
> chore: deprecate useAsyncStorage

- src/components/Messaging/ComposeInputBar.tsx
- src/components/Messaging/SearchRecipientsModal.tsx
- src/hooks/useAppConfig.tsx
- src/screens/ComposeMessageScreen.test.tsx
- src/screens/ComposeMessageScreen.tsx
- Improve the compose new message screen by sorting providers and patients into two separate fields.
- Only providers will be given the patient field which has a limit of one patient.
https://github.com/lifeomic/react-native-sdk/assets/76954025/b679b82a-896b-4d84-9bbe-1a03cf28e616
> fix: Improve the compose new message screen

- src/screens/MessageScreen.tsx
- Need to allow for changing the color of this icon
Without style options:
> fix: Add Style Settings for Compose Message Icon

- src/screens/MessageScreen.tsx
- Shrink multi-icons to match size of single icon
- Reduce excess spacing on both sides of the icon
> fix: Shrink icons, remove excess whitespace

- src/screens/ProfileScreen.tsx
This PR is trying to better match styles found in Figma file. This is my first commit to a React Native project so I thought I'd start small.
- Adjust font sizes
- Add fields container padding
- Adjust spacing between fields
- Add divider and adjust top margin
BEFORE | AFTER
-- | --
https://github.com/lifeomic/fountain-life-member-app/pull/152
> fix: Adjust profile screen padding, typography and add divider

- src/types/fhir-api-types.ts
We'll be fetching a patient's practitioner, so we're adding the type to the REST API hooks.
- Adding `Practitioner` to `FhirResourcesByName`.
N/A
> feat: add Practitioner to FhirResourcesByName

- README.md
- example/AppDemo.tsx
- example/storybook/stories/CustomScreenInjection/CustomScreenInjection.stories.tsx
- example/storybook/stories/ExampleApp/ExampleApp.stories.tsx
- src/common/DeveloperConfig.ts
- src/common/LoggedInProviders.tsx
- src/common/RootProviders.tsx
- src/hooks/useActiveAccount.tsx
- src/hooks/useNotifications.tsx
- src/hooks/useUser.ts
- src/navigators/RootStack.tsx
- src/navigators/index.ts
- src/navigators/types.tsx
- src/screens/AuthedAppTileScreen.test.tsx
- src/screens/CircleThreadScreen.tsx
I'm slowly working my way toward being able to merge #450. A couple light refactors are needed before that change can be pushed through safely.
This PR proposes a refactor which will result in more predictable behavior of hooks, API interactions, and more throughout the SDK.
The core change:
- the stack of `LoggedInProviders` is now _only_ rendered if+when the user is logged in.
- the `LoginScreen` is now rendered _instead_ of the list of `LoggedInProviders` when the user is logged out.
- removed `RootStack` altogether, since it became a pure-forward to `LoggedInStack`.
This unlocks a couple nice behaviors:
- Any authenticated calls to `useQuery` (which is _every_ call to `useQuery`) no longer need to implement the `enabled: isLoggedIn` check -- the component simply won't be rendered …
> feat!: move LoginScreen outside of LoggedInProviders

- UPGRADING.md
- src/common/DeveloperConfig.ts
- src/common/RootProviders.tsx
- src/components/BrandConfigProvider/BrandConfigProvider.tsx
- src/components/BrandConfigProvider/index.ts
#462 broke a particular use case: using a custom `BrandConfigProvider` to style the LoginScreen. This PR introduces a fix to that flow, and guidance for upgrading.
> fix: support specifying a 'brand' via DeveloperConfig

- src/common/RootProviders.tsx
- src/components/LogoHeader.tsx
- src/components/MessagesTile/MessagesTile.test.tsx
- src/components/MessagesTile/MessagesTile.tsx
- src/components/Messaging/ComposeInputBar.tsx
- src/components/tiles/TilesList.tsx
- src/hooks/useLogoHeaderDimensions.tsx
- src/navigators/BottomNavigationBar.tsx
- src/navigators/TabNavigator.tsx
- src/screens/ComposeMessageScreen.test.tsx
- src/screens/ComposeMessageScreen.tsx
- Fixes the keyboard avoiding view to correctly account for the header and logoHeader
- Fixes the messageTile icon display (wasn't using theme on iOS and wasn't visible on Android)
- Reworks the tabs so that the material (paper) tabs use the BottomTabsBar Navigator so that we can get the height of the tabs (createMaterialBottomTabNavigator is removed in React Native Navigation 6.x so this will help with an eventual upgrade)
<table>
<tr>
<td><video src="https://github.com/lifeomic/react-native-sdk/assets/2295908/89be5dbe-5c8e-4eb7-93d8-a42949628cc8" />
<td><video src="https://github.com/lifeomic/react-native-sdk/assets/2295908/aa9bd6aa-7b1a-4cd6-a908-24877a4c9e8f" />
</table>
> fix: Make Message View Avoid Keyboard

- src/components/tiles/TilesList.tsx
- src/screens/DirectMessagesScreen.test.tsx
- src/screens/DirectMessagesScreen.tsx
- Fixes a bug on iOS for Direct Message Input where there was too much space added (accounted for tabs which should only happen on android)
- Fixes a missing key warning
<table>
<tr>
<td><b>Before
<td><b>After
<tr>
<td><img src="https://github.com/lifeomic/react-native-sdk/assets/2295908/5522e3cf-8f59-4549-b33a-dbbc19dc9e05" />
<td><img src="https://github.com/lifeomic/react-native-sdk/assets/2295908/ba0f02e8-b7d9-44cf-902b-8864f001b90e" />
</table>
> fix: Layout Issue for Direct Messages Input

- UPGRADING.md
- src/components/TodayBadge.test.tsx
- src/components/TrackTile/hooks/useAxiosTrackTileService.ts
- src/hooks/Circles/useJoinCircles.tsx
- src/hooks/todayTile/useTodayTasks.tsx
- src/hooks/useActiveAccount.test.tsx
- src/hooks/useActiveAccount.tsx
- src/hooks/useActiveProject.test.tsx
- src/hooks/useActiveProject.tsx
- src/hooks/useAppConfig.tsx
- src/hooks/useConsent.ts
- src/hooks/useFhirClient.tsx
- src/hooks/useOnboardingCourse.tsx
- src/hooks/usePushNotifications.test.tsx
- src/hooks/useSetUserProfileEffect.test.ts
- src/hooks/useSetUserProfileEffect.ts
- src/hooks/useWearableBackfill.tsx
- src/navigators/LoggedInStack.tsx
- src/navigators/types.tsx
- src/screens/AppTileScreen.test.tsx
- src/screens/AuthedAppTileScreen.tsx
- src/screens/InviteRequiredScreen.tsx
- src/screens/MyDataScreen.test.tsx
- src/screens/ProfileScreen.test.tsx
- src/screens/ProfileScreen.tsx
**Reviewers:** I've separated the changes here into dedicated commits for maximum reviewability. I highly recommend reviewing by commit, with **Hide Whitespace Changes** turned on.
The commits:
- Modifications to the type contract and implementation of `useActiveProject`, as well as the other core changes to "move" the InviteRequired screen higher up the tree.
- Update internal references to `useActiveProject` to pull out any now-dead conditional logic around the return values.
- Update tests to reflect the changes above^.
- Entirely unrelated: adding a test suite to `usePushNotifications`, to put this PR above the coverage threshold requirement.
I performed in-depth manual testing of this change in internal apps -- I confirmed that during the various onboarding/login flows, the previous …
> feat!: require project to be loaded before rendering children

- src/common/DeveloperConfig.ts
- src/hooks/useConsent.ts
- src/screens/ConsentScreen.test.tsx
- src/screens/ConsentScreen.tsx
- Support passing a custom Consent screen, similar to custom login and home screens 
- The custom component will be provided props to be able to render and act on the consent
> feat: support custom consent screen

- src/hooks/useConsent.test.tsx
- src/hooks/useConsent.ts
- src/screens/ConsentScreen.test.tsx
- src/screens/ConsentScreen.tsx
- Following up on an early suggestion to switch this to use `mutate` over `mutateAsync`, makes using it a bit simpler especially in the custom screen flow
> fix: consent screen use mutate over async mutate

- src/hooks/useActivities.tsx
- src/hooks/useConsent.test.tsx
- src/hooks/useConsent.ts
- src/screens/ConsentScreen.test.tsx
- src/screens/ConsentScreen.tsx
If a user has been enrolled into a program before their first login, we need to refresh their activity list whenever they accept a consent. Accepting consent can result in new activities showing up.
> FLME-340: invalidate activities list when consent is accepted

- src/types/fhir-api-types.ts
I hit an issue with `one-query` + the FHIR API. The patient service API does validation between the ID in the path param and the ID in the data payload. If they do not match, it throws an error. I checked out the `one-query` code, and we do remove any path param properties from the data payload. 
To avoid having to ship API changes right now, I'm just fixing this issue client side by changing `:id` to `:resourceId` in the `one-query` routes, that way, they payload won't replace `id`. We'll just have to specify both `resourceId` and `id` in the payload when calling `one-query`.
N/A
> fix(FHIR API): path param :id to :resourceId

- src/hooks/useSubjectProjects.tsx
By just putting the project list in this query key, it makes it safe for us to modify the larger `useMe` result without invalidating this query.
> fix: slim down query key for subjects

- src/components/Invitations/InviteNotifier.test.ts
- src/components/Invitations/InviteNotifier.ts
- src/components/Invitations/InviteProvider.test.tsx
- src/components/Invitations/InviteProvider.tsx
I'm working the existing issue that flashes the InviteRequired screen. To make subsequent changes cleaner, removing these currently defunct invitation events.
> fix: remove unused invite events

- src/components/AuthedWebApplet.tsx
- src/screens/AuthedAppTileScreen.test.tsx
- src/screens/AuthedAppTileScreen.tsx
We need to do tighter customization of the surveys screen in an internal app. This PR extracts the "core" logic of `AuthedAppTileScreen` into an `AuthedWebApplet` component.
This PR contains **no behavior changes**, as evidenced by the unchanged tests.
> FLME-300 [part 1]: extract AuthedWebApplet component

- src/types/fhir-api-types.ts
- Add `patient` search param Observations in fhir-api-types so users can get their own Observations
> feat: FLME-323 add patient to Observation SearchParams

- src/components/Messaging/ComposeInputBar.tsx
- src/screens/ComposeMessageScreen.tsx
- Explicitly set the text colors so they appear correctly on android with dark mode
<table>
<tr>
<td><b>iOS Light
<td><b>iOS Dark
<td><b>Android Light
<td><b>Android Dark
<tr>
<td><img width="428" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/7659210d-2c33-42df-9c1e-f83fa687a1e0">
<td><img width="422" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/8376b7ac-a2bc-454c-9c72-daff744630e0">
<td><img width="302" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/0f0808eb-d3d7-49e8-b448-91d24cf1942b">
<td><img width="300" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/4b9792b7-595d-455d-a625-6934ccfdf51b">
<tr>
<td><img width="422" alt="image" …
> Fix Android Colors on Dark Mode

- src/types/fhir-api-types.ts
Unfortunately, this resource type does _not_ currently support a status filter or date sorting. Tested this by hitting the api directly with different options
as fyi sorting by date for observations works something like this
```
const { data } = await this.client.get(
`/${encodeURIComponent(account)}/dstu3/Observation`,
{
params: {
patient: 'ef876b82-92d8-433b-b0e6-86365116401d',
date: ['gt2022-12-12T19:55:24.079Z', 'lt2023-29-12T19:55:24.079Z'],
_sort: '-date' | 'date',
},
},
);
```
> feat: add operations for fhir procedure request resource

- src/types/fhir-api-types.ts
Adding support for `DocumentReference`
> feat: add DocumentReference FHIR resource typing

- src/types/rest-types.ts
> feat: add subject param

- src/hooks/useActivities.tsx
- Just exporting `getActivitiesQueryDocument` for individual use when necessary. We're needing this in our client.
N/A
> fix: export getActivitiesQueryDocument

- src/components/Invitations/InviteProvider.tsx
This handling seems to have become incorrect over the past few months. This makes it correct.
> fix: improve invite already accepted handling

- src/components/MyData/SleepChart/useSleepChartData.test.ts
- src/components/MyData/SleepChart/useSleepChartData.ts
- Wearables such as HealthKit can collect data from multiple wearables. This can result in overlapping sleep data that describes the same sleep event. This change adds logic to only use a single observation per day when displaying the sleep information. We group all data by the start of the effective day and then use the observation with the most components (attempt to use the most granular data).
> Handle Same Day Data in Sleep Charts

- src/components/MyData/SleepChart/MultiDayChart.tsx
- src/components/MyData/SleepChart/index.test.tsx
- src/components/MyData/SleepChart/useSleepChartData.test.ts
- We are changing how sleep analysis is ingested so this adds logic to support observations with either a valuePeriod or a valueQuantity represented as unitsofmesaure/minutes.
> Support valueQuantity for Sleep Duration When Coded in Minutes

- src/components/MyData/SleepChart/DailyChart.tsx
- src/components/MyData/SleepChart/MultiDayChart.tsx
- src/components/MyData/SleepChart/SleepSummary.tsx
- src/components/MyData/SleepChart/index.test.tsx
- src/components/MyData/SleepChart/index.tsx
- src/components/MyData/SleepChart/useSleepDisplay.ts
- Adds a summary view to the sleep analysis chart
- Adds a visual representation of the total of each stage type to the multiday view
https://github.com/lifeomic/react-native-sdk/assets/2295908/7af30bd2-019b-4157-a690-93124afaf7a7
> Add Sleep Summary View

- src/components/MessagesTile/MessagesTile.tsx
- src/hooks/useConversations.test.tsx
- src/hooks/useConversations.ts
- Adds logic to filter the conversation notification badge to only be true if there are conversations within the message tile that have unread messages
> fix: Filter Conversation Notification Badge

- src/common/RootProviders.tsx
- src/hooks/useOAuthFlow.test.tsx
- src/hooks/useOAuthFlow.tsx
Alternative pr to #521. Instead of allowing a consumer to intercept the config at the time an action is about to take place, this provides a function that takes the current auth result and then will return the auth config 
Also noticed the setup function for the tests here was async and didn't need to be. Likely drifted from a time it was required
> feat: allow for providing dynamic auth config based on current auth result

- src/hooks/useOAuthFlow.test.tsx
- src/hooks/useOAuthFlow.tsx
We found out there was an infinite render cycle caused by the dynamic config getter. The issue was caused by the `authResult` being different every time, which triggered the `useMemo` to be calculated infinitely.
We really only needed the `accessToken` from `authResult`, and since that's just a string, it fix the infinite render cycle since we can just pass the string as the `useMemo` dependency. 
The consumer does have to make sure that the getter is stable on their end though.
I confirmed this changes locally.
> fix: dynamic oauth config getter

- src/common/RootProviders.tsx
> feat: allow for providing safe area provider props

- src/hooks/useConsent.ts
- src/screens/ConsentScreen.tsx
- Handle multiple consent assigments
https://github.com/lifeomic/react-native-sdk/assets/76954025/f1296030-4f7e-4765-b853-042af2f27374
> feat: Add handling for multiple consents

- src/components/Invitations/InviteNotifier.ts
- src/components/Invitations/InviteProvider.tsx
- src/screens/LoginScreen.test.tsx
- src/screens/LoginScreen.tsx
- Adds the ability to set some loading state for an incoming invite
- Adds logic to the login screen to disable and trigger a loading wheel when an invite is being loaded
- Adds the ability to inspect the invitation error with a long press
https://github.com/lifeomic/react-native-sdk/assets/2295908/4d7f8a14-61b0-47b3-b79b-55a2f7ec03b8
> feat: Add Invite Loading State

- src/components/Invitations/InviteNotifier.ts
- If a inviteLoadingStateChanged listener mounts after the event has been emitted, it misses the state value. This updates the logic to emit the most recent value when the listener is added.
> Emit Latest Invite State Value on Subscribe

- src/common/DeveloperConfig.ts
- src/hooks/useOAuthFlow.tsx
- Add config option to not forward inviteId and evc to the auth session
> Allow skip invite params

- src/common/Analytics/AnalyticsEvents.ts
- src/components/Invitations/InviteProvider.tsx
- src/hooks/useOAuthFlow.tsx
- src/screens/ConsentScreen.test.tsx
- src/screens/ConsentScreen.tsx
- src/screens/InviteRequiredScreen.tsx
- src/screens/LoginScreen.tsx
- Track scenarios related to onboarding, login, etc.
> fix: Add additional analytics hooks

- src/screens/InviteRequiredScreen.tsx
- Add a default color so that the invite required screen doesn't change when dark mode is enabled
- Add text overrides to allow for an easy hook to change the messaging on the invite required screen
> fix: Default background color and allow text overrides via styles

- src/components/Messaging/SearchRecipientsModal.tsx
- src/screens/MessageScreen.tsx
- Add explanation for when the messages screen is empty
- Add explanation for when the compose messaging screen has no recipients
> fix: Add messaging placeholder

- src/screens/ConsentScreen.tsx
- Wrapping Markdown with a Text block breaks the ability for text to wrap on Android
- Tested on iOS and Android
> fix: Android markdown text not wrapping

- src/common/LoggedInProviders.tsx
- src/components/AppConfigSwitcher.tsx
- src/components/AppConfigSwitcherButton.tsx
- src/hooks/rest-api.tsx
- src/hooks/useAppConfig.test.tsx
- src/hooks/useAppConfig.tsx
- src/hooks/useTabsConfig.test.tsx
> feat: Add app switcher button

- example/storybook/stories/CustomAppTileScreen.stories.tsx
- src/common/DeveloperConfig.ts
- src/components/MessagesTile/MessagesTile.test.tsx
- src/components/MessagesTile/MessagesTile.tsx
- src/components/tiles/BoxTile.tsx
- src/components/tiles/ListTile.tsx
- src/components/tiles/Tile.test.tsx
- src/components/tiles/Tile.tsx
- src/components/tiles/TilesList.tsx
- src/screens/HomeScreen.tsx
- Adds a developerConfig option to switch the presentation mode of the app tile list
https://github.com/lifeomic/react-native-sdk/assets/76954025/f73a2ae8-be9e-4286-847a-b6e3272ccda6
> feat: Add column tile layout

- example/AppDemo.tsx
- src/common/DeveloperConfig.ts
- src/components/OAuthLoginButton.tsx
- src/hooks/useOAuthFlow.tsx
- Add dialog to direct user's to invite flow on first login attempt
https://github.com/lifeomic/react-native-sdk/assets/76954025/0c946bae-fdd5-44f8-92f7-77ca9346f8c8
> feat: Add first time login dialog

- src/hooks/Circles/usePrivatePosts.ts
- src/screens/DirectMessagesScreen.tsx
- src/screens/MessageScreen.tsx
- Adds some basic markdown support to the DirectMessageScreen and the MessageScreen (list of messages)
- Adds formatting of email, phone, and urls to the DirectMessageScreen and the MessageScreen (list of messages)
-  `[text](https://google.com)` - renders a link. Example:  [text](https://google.com)
- `***text***` - renders text as bold and italic. Example:   ***text***
- `**text**` or `__text__` - renders text as bold. Example:   **text**
- `*text*` or `_text_` - renders text as italic. Example:   _text_
- `~~text~~` - renders text as strikethrough. Example:   ~~text~~
- `![image](https://reactnative.dev/img/tiny_logo.png)` - renders an image in it's own bubble. Example:
Note: Markdown does not support nested styling. i.e. Markdown like `**Bold text with _emphasis_ text**` will not …
> Add Messaging Markdown (light) Support

- src/common/DeveloperConfig.ts
- src/hooks/useActiveProject.tsx
- In the event that we are expecting auto-patient mapping to occur do not show the invite required screen but instead keep querying for subjectId and project.
> feat: Add option to wait for subjectId

- src/screens/DirectMessagesScreen.tsx
- Adjusts the default image styles to not have a background and not display the time
- Adds logic to make the image display with the correct aspect ratio
- Tweaks the lightbox settings to avoid the black background display when interacting with the image (open/close)
<table>
<tr>
<td><b>Before
<td><b>After
<tr>
<td><img src="https://github.com/lifeomic/react-native-sdk/assets/2295908/68161418-f41f-4a9d-9427-b5fe8be1141f" />
<td><img src="https://github.com/lifeomic/react-native-sdk/assets/2295908/817d390a-4386-461f-ad56-c8d7151004a4" />
</table>
Text messages still have bubbles:
> fix: Modify image message bubble styles

- src/components/ActivityIndicatorView.tsx
- src/hooks/useActiveProject.tsx
- Add logout button that appears after 60 seconds have elapsed
- Fix test align
https://github.com/lifeomic/react-native-sdk/assets/76954025/7b94f5ab-2d95-4ae9-91c7-6e132ed6c7d7
> Add logout button to bail

- src/screens/ComposeMessageScreen.tsx
- Your changes...
<table>
<tr>
<td><b>Before
<td><b>After
<tr>
<td><img width="393" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/3dca3d72-c230-469e-b6ea-a28ff4d8ebae">
<td><img width="411" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/1ca64713-f84d-4932-ae37-a4c695496462">
</table>
> fix: To Chip Sizing for Font Scaling

- src/screens/DirectMessagesScreen.tsx
- Fixes the border style for the pending images view
<table>
<tr>
<td><b>Before
<td><b>After
<tr>
<td><img width="370" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/3e514f99-7fdf-47ca-b070-2511ab63a217">
<td><img width="375" alt="image" src="https://github.com/lifeomic/react-native-sdk/assets/2295908/462d6852-6504-4de9-b6a6-212bde0c6b7a">
</table>
> fix: Fix Pending Image Border Style

- example/AppDemo.tsx
- example/storybook/helpers/oauthConfig.ts
- src/hooks/useActiveProject.tsx
- Allow specifying the example apps account parameter from the config file
- Throttle query retries
> Retry queries on interval

- src/common/LoggedInProviders.tsx
- src/hooks/useOAuthFlow.tsx
- Move priorLoginDetected flag so it gets set if a user is already logged in
> fix: set initial login flag so it gets set if already logged in

- src/components/MyData/SleepChart/DailyChart.tsx
- src/components/MyData/SleepChart/MultiDayChart.tsx
- src/components/MyData/SleepChart/useSleepChartData.ts
- src/screens/MyDataScreen.tsx
- Fixes a bug where the start and end dates were null, causing the app to crash
- Removes data selector on empty charts to prevent empty selection bar/flag
- Hides stage bar if no components exist. Before the chart would render an misaligned arbitrary bar
- Fixes a bug where the chart wrapper did not fill the full width of its parent, resulting in the summary view being squished
> fix: Sleep Chart Bug Fixes

- src/common/DeveloperConfig.ts
- src/hooks/useConsent.ts
- Add flag to force the app to wait until a new consent is assigned if there are no active consents
- This is required to handle race conditions between first sign in and auto-patient creation.
> feat: Add config option to require an active consent
